// GENERATED by `pnpm run gen:narrative` from src/core/content/narrative/asks.md — DO NOT EDIT.
// Hand edits here are drift by definition: edit the markdown source and regenerate
// (the gen-narrative verify gate rebuilds this file and byte-compares it).
// Data only — the types + helpers stay hand-written in asks.ts, which re-exports this.

import { NPC_NAME } from './voices';
import type { GenAskDef } from './asks';

export const ASK_DEFS: readonly GenAskDef[] = [
  {
    id: 'genemon-house-standing',
    person: 'genemon',
    rungMin: 'R0',
    label: '“How do I stand with the house?”',
    refresh: 'rung',
    lines: [
      {
        id: 'the-book-says',
        voice: 'steward',
        speaker: NPC_NAME.genemon,
        text: '“The book says what it says. My ledger holds one line for you — what you are to this house today is written there, and today it reads: nothing more, nothing less.”',
      },
    ],
  },

  {
    id: 'genemon-house-wants',
    person: 'genemon',
    rungMin: 'R0',
    label: '“What does the house want of me?”',
    refresh: 'rung',
    native: 'house-wants',
  },

  {
    id: 'soan-body-mend',
    person: 'soan',
    rungMin: 'R0',
    label: '“Have a look at me, would you?”',
    refresh: 'health',
    native: 'body-mend',
  },

  {
    id: 'ohisa-kitchen-season',
    person: 'ohisa',
    rungMin: 'R0',
    label: '“What’s the kitchen cooking?”',
    refresh: 'season',
    lines: [
      {
        id: 'what-the-season-gives',
        voice: 'steward',
        speaker: NPC_NAME.ohisa,
        text: '“What the season gives, we cook. The pot doesn’t argue with the calendar and neither do I — come at mealtime and you’ll see for yourself.”',
      },
    ],
  },

  {
    id: 'oyae-village-news',
    person: 'oyae',
    rungMin: 'R1',
    label: '“Any word from the village?”',
    refresh: 'season',
    lines: [
      {
        id: 'word-comes-up-the-road',
        voice: 'villager',
        speaker: NPC_NAME.oyae,
        text: '“Word comes up the road with me every morning — most of it not worth the carrying. Ask me again when the season turns; that’s when the village finds things worth saying.”',
      },
    ],
  },

  {
    id: 'shinnosuke-what-are-you-doing',
    person: 'shinnosuke',
    rungMin: 'R0',
    label: '“What are you up to?”',
    lines: [
      {
        id: 'watching-you',
        voice: 'steward',
        speaker: NPC_NAME.shinnosuke,
        text: '“Watching you. Grandfather says you came from the weir with no name on you. I’ve never met anyone who wasn’t anyone before.”',
      },
    ],
  },
];
