// GENERATED by `pnpm run gen:narrative` from src/core/content/narrative/asks.md — DO NOT EDIT.
// Hand edits here are drift by definition: edit the markdown source and regenerate
// (the gen-narrative verify gate rebuilds this file and byte-compares it).
// Data only — the types + helpers stay hand-written in asks.ts, which re-exports this.

import { NPC_NAME } from './voices';
import type { GenAskDef } from './asks';

export const ASK_DEFS: readonly GenAskDef[] = [
  {
    id: 'genemon-house-standing',
    person: 'genemon',
    rungMin: 'R0',
    label: '“What does your book say of me?”',
    refresh: 'rung',
    lines: [
      {
        id: 'the-book-says',
        voice: 'steward',
        speaker: NPC_NAME.genemon,
        text: '“Your line stands where the book set it this morning — entered, current, carried forward, nothing owing past what the page shows. Most men wait to be read to. You ask; I have made a note of that.”',
      },
    ],
  },

  {
    id: 'genemon-house-wants',
    person: 'genemon',
    rungMin: 'R0',
    label: '“Steward. What does the house ask of me?”',
    refresh: 'rung',
    native: 'house-wants',
  },

  {
    id: 'soan-body-mend',
    person: 'soan',
    rungMin: 'R0',
    label: '“Doctor. Look me over, when your rounds allow.”',
    refresh: 'health',
    native: 'body-mend',
  },

  {
    id: 'ohisa-kitchen-season',
    person: 'ohisa',
    rungMin: 'R0',
    label: '“What’s in the pot?”',
    refresh: 'season',
    lines: [
      {
        id: 'what-the-season-gives',
        voice: 'steward',
        speaker: NPC_NAME.ohisa,
        text: '“What comes in the door with the dirt still on it, that goes in the pot — that and salt, and salt we still have. If the season means to be kinder than the last one — well. You’ll smell it from the woodshed before I say a word.”',
      },
    ],
  },

  {
    id: 'oyae-village-news',
    person: 'oyae',
    rungMin: 'R1',
    label: '“What do they say in the village?”',
    refresh: 'season',
    lines: [
      {
        id: 'word-comes-up-the-road',
        voice: 'villager',
        speaker: NPC_NAME.oyae,
        text: '“The baskets go down full of washing and come back up full of what they say — none of it mine, I only carry. They’re talking, they always are; when they say a thing worth setting the load down for, you’ll have it the same morning I do.”',
      },
    ],
  },

  {
    id: 'shinnosuke-what-are-you-doing',
    person: 'shinnosuke',
    rungMin: 'R0',
    label: '“No work of your own?”',
    lines: [
      {
        id: 'watching-you',
        voice: 'steward',
        speaker: NPC_NAME.shinnosuke,
        text: '“My letters — only the ink dries faster than I can write it, so I’m watching you work instead. How do you tie a load one-handed, and who taught you?”',
      },
    ],
  },

  {
    id: 'genemon-word',
    person: 'genemon',
    rungMin: 'R0',
    label: '“Steward. Have you a word for me?”',
    native: 'u9-genemon',
  },

  {
    id: 'kihei-word',
    person: 'kihei',
    rungMin: 'R0',
    label: '“Drillmaster. Have you an order for me?”',
    native: 'u9-kihei',
  },

  {
    id: 'soan-word',
    person: 'soan',
    rungMin: 'R0',
    label: '“Doctor. If you can spare me a moment.”',
    native: 'u9-soan',
  },

  {
    id: 'ohisa-word',
    person: 'ohisa',
    rungMin: 'R0',
    label: '“O-Hisa. A word, if the pot can wait.”',
    native: 'u9-ohisa',
  },

  {
    id: 'shinnosuke-word',
    person: 'shinnosuke',
    rungMin: 'R0',
    label: '“You have questions. Ask one.”',
    native: 'u9-shinnosuke',
  },

  {
    id: 'naoyuki-word',
    person: 'naoyuki',
    rungMin: 'R0',
    label: '“Master Naoyuki. What would you have me do?”',
    native: 'u9-naoyuki',
  },

  {
    id: 'toku-word',
    person: 'toku',
    rungMin: 'R0',
    label: '“Grandmother. May I have a word?”',
    native: 'u9-toku',
  },

  {
    id: 'oyae-word',
    person: 'oyae',
    rungMin: 'R0',
    label: '“What do they say down the road, O-Yae?”',
    native: 'u9-oyae',
  },

  {
    id: 'matsuzo-word',
    person: 'matsuzo',
    rungMin: 'R0',
    label: '“What news at the weir, Matsuzō?”',
    native: 'u9-matsuzo',
  },

  {
    id: 'iori-word',
    person: 'iori',
    rungMin: 'R0',
    label: '“A word before you go, traveler?”',
    native: 'u9-iori',
  },

  {
    id: 'oume-word',
    person: 'oume',
    rungMin: 'R0',
    label: '“How do the fields stand, O-Ume?”',
    native: 'u9-oume',
  },

  {
    id: 'rokusuke-word',
    person: 'rokusuke',
    rungMin: 'R0',
    label: '“Anything doing, Rokusuke?”',
    native: 'u9-rokusuke',
  },

  {
    id: 'matsuzo-waters',
    person: 'matsuzo',
    rungMin: 'R0',
    label: '“Is the weir holding?”',
    native: 'waters-hint',
  },

  {
    id: 'oume-margins',
    person: 'oume',
    rungMin: 'R0',
    label: '“Hard ground this year?”',
    native: 'margins-hint',
  },

  {
    id: 'rokusuke-timber',
    person: 'rokusuke',
    rungMin: 'R0',
    label: '“Does the wood cut clean?”',
    native: 'timber-hint',
  },
];
