// GENERATED by `pnpm run gen:narrative` from src/core/content/narrative/cold-open.md — DO NOT EDIT.
// Hand edits here are drift by definition: edit the markdown source and regenerate
// (the gen-narrative verify gate rebuilds this file and byte-compares it).
// Data only — the types + helpers stay hand-written in coldOpen.ts, which re-exports this.

export const COLD_OPEN = {
  weir: 'The river gives you up at the weir. You keep none of it in order: hands in your collar, gravel under your back, the sky white and near, water leaving you in coughs. A stone jizō watches from the bank, rice at its feet, nobody on the road who could have left it. Someone says, carry him up, then. Then nothing.',
  wake: 'Straw. A low roof. A fire kept small. Something surfaces — a knot, a road in grey rain — and goes down again before you can put a hand to it. You have been three days in a room you have never seen.',
  dream:
    'Something surfaces — a knot, a road in grey rain — and goes down again before you can put a hand to it.',
  daybook:
    'One man, name unknown. Taken at the weir. Fed, three days. Condition, poor; hands, good.',
  daybookVerbs: 'Rakes; hauls. Wage: meals.',
  rake: 'The court is long and the rake is short. You work it in rows, corner to gate, until the gravel shows its lines again. Nobody watches. The rows stay.',
  haul: 'Two buckets on a yoke, well to kitchen, forty paces each way. By the fourth trip the jars stop ringing hollow. The kitchen does not thank the water. It uses it.',
} as const;
