// GENERATED by `npm run gen:narrative` from src/core/content/narrative/cold-open.md — DO NOT EDIT.
// Hand edits here are drift by definition: edit the markdown source and regenerate
// (the gen-narrative verify gate rebuilds this file and byte-compares it).
// Data only — the types + helpers stay hand-written in coldOpen.ts, which re-exports this.

import { NAMES } from './names';

export const COLD_OPEN = {
  wake: "You open your eyes. Straw beneath you, the smell of wet rice, a low roof you do not know. A cold spring — the ninth year of An'ei — though the year is as lost to you as your name.",
  grounding: `"You're awake." ${NAMES.physician} the physician sits back on his heels. "No kami carried you off, whatever the village wants to believe. A flood took you, and a blow to the head took the rest. Bodies forget. Given work and rice, they also mend."`,
  dream:
    "Something surfaces and is gone — a porter's knot, a road in grey rain, a name you cannot keep hold of.",
  bodyReveal: 'You take stock of yourself: bruised, hollow, half-starved — but breathing.',
  riceReveal: `Rice lies scattered across the ${NAMES.house} grain-store floor. Spilled stores are waste — and clearing waste is a kind of work, if you set your hands to it.`,
  coinReveal:
    'Copper coin, warm from another hand — your first wage. Rice fills a belly; coin is what the world takes in trade for everything a belly is not.',
  restReveal: 'Your arms are leaden. You could rest a moment against the cool post.',
  restAct: 'You rest against the post. The ache dulls; the light through the slats shifts.',
} as const;
