// GENERATED by `npm run gen:narrative` from src/core/content/narrative/dialogue.md — DO NOT EDIT.
// Hand edits here are drift by definition: edit the markdown source and regenerate
// (the gen-narrative verify gate rebuilds this file and byte-compares it).
// Data only — the types + helpers stay hand-written in dialogue.ts, which re-exports this.

import { NAMES } from './names';
import type { DialogueDef } from './dialogue';

export const DIALOGUES: readonly DialogueDef[] = [
  {
    id: 'genemon-open',
    speaker: NAMES.elder,
    lines: [
      {
        id: 'gen-greet',
        speaker: NAMES.elder,
        voice: 'steward',
        text: `On your feet, then. I am ${NAMES.elder}, steward of this house, and I keep the little it has left to keep. You'll not remember any of it, so hear it plain: the ${NAMES.house} are samurai still — on the lord's rolls, if nowhere in the granary.`,
      },
      {
        id: 'gen-stores',
        speaker: NAMES.elder,
        voice: 'steward',
        text: 'Mind the floor before you mind your head. Half a season’s stores lie spilled and trodden where the kura door gave way in the rains. Rice on the boards is rice the house has lost — and this house has done losing enough for three lifetimes.',
      },
      {
        id: 'gen-rake',
        speaker: NAMES.elder,
        gate: (flags) => flags.raked === true,
        voice: 'steward',
        text: 'So you put your hands to it. Rake what grain is still whole back toward the basket, a fistful at a time. We reckon a samurai house’s worth in koku — a year’s eating for one man — and every basket you save us is a measure we need not go begging to the lord to make good.',
      },
      {
        id: 'gen-keep',
        speaker: NAMES.elder,
        gate: (flags) => flags.raked === true,
        voice: 'steward',
        text: "Clear it without my standing over you, and you'll have earned your rice and a dry corner to sleep in. I'll make you no grander promise than that. In this house, none of us holds one.",
      },
      {
        id: 'gen-kept',
        speaker: NAMES.elder,
        gate: (flags) => flags.raked === true,
        voice: 'narrator',
        text: `"...You don't shirk the work," ${NAMES.elder} says, eyeing the cleared boards and the filling basket. "The house has had its fill of hands that do. Earn your keep, and a place here is yours."`,
      },
    ],
  },

  {
    id: 'kihei-intro',
    speaker: NAMES.drillmaster,
    lines: [
      {
        id: 'kihei-1',
        speaker: NAMES.drillmaster,
        text: `${NAMES.drillmaster}, master-at-arms — what's left of the office. I keep a drill yard of warped poles and grey-haired men, and I wait on someone with the spine to swing them.`,
      },
      {
        id: 'kihei-2',
        speaker: NAMES.drillmaster,
        text: "When your legs will hold you and your head has stopped ringing, come and find me there. A house at the frayed edge of the lord's favour needs more than farmhands — and I would see what the flood left in your arms.",
      },
    ],
  },

  {
    id: 'soan-intro',
    speaker: NAMES.physician,
    lines: [
      {
        id: 'soan-greet-grateful',
        speaker: NAMES.physician,
        memGate: (m) => m.soan?.regard === 'grateful',
        voice: 'physician',
        text: `${NAMES.physician} looks up. "You came back on your own feet — I told you the wits mend last. Sit. Let's see what's still bitter to steep."`,
      },
      {
        id: 'soan-greet-curt',
        speaker: NAMES.physician,
        memGate: (m) => m.soan?.regard !== 'grateful',
        voice: 'physician',
        text: `${NAMES.physician} does not look up. "Still no patience for a physician, I see. Sit anyway. This will sting, and you'll thank me later — or you won't."`,
      },
      {
        id: 'soan-1',
        speaker: NAMES.physician,
        voice: 'physician',
        text: `${NAMES.physician}. I set what's broken and steep what's bitter, and I tell Asagiri there are no kami abroad in the reeds, however much the village would prefer there were.`,
      },
      {
        id: 'soan-2',
        speaker: NAMES.physician,
        voice: 'physician',
        text: 'Your wits will settle as the swelling does — eat when there is rice, rest when there is none, and don’t let the old women talk a fever into a haunting. That is the whole of my craft, and the better part of my counsel.',
      },
    ],
  },
];
