// GENERATED by `npm run gen:narrative` from src/core/content/narrative/flavor.md — DO NOT EDIT.
// Hand edits here are drift by definition: edit the markdown source and regenerate
// (the gen-narrative verify gate rebuilds this file and byte-compares it).
// Data only — the types + helpers stay hand-written in flavor.ts, which re-exports this.

export const FLAVOR = {
  mendHint: 'A worn edge is mended by hands the house has come to trust.',
} as const;
