// GENERATED by `pnpm run gen:narrative` from src/core/content/narrative/flavor.md — DO NOT EDIT.
// Hand edits here are drift by definition: edit the markdown source and regenerate
// (the gen-narrative verify gate rebuilds this file and byte-compares it).
// Data only — the types + helpers stay hand-written in flavor.ts, which re-exports this.

export const FLAVOR = {
  mendHint: 'The edge is going. Not yet mine to mend — climb higher, then set it right.',
  estateSourceFields:
    "Entered: rice from the new paddies, credited to the house's own account. The old books carried this line once; it is carried again.",
  estateSourceStores:
    'Entered: the granary takes in more than it pays out. A full storehouse needs no remark — this one has earned it all the same.',
  estateSourceWorkshop:
    "Entered: one piece, workshop-made, sold under the house's mark. The mark will outlast the ink of this entry.",
  estateSourceWatch:
    "Entered under losses: nothing. The trouble came to the gate and was turned there; the ledger's emptiest lines are the dearest bought.",
  estateSourceTreasury:
    'Entered: rice sold at market, the coin set down in the house books — owed to no man. The steward has waited some years to write that word.',
  lacquerHint0:
    "Cut wood at the yard's edge and the smell comes back on the axe — pine, mostly, but under it something else, thin and bitter, like nothing else in the stack.",
  lacquerHint1:
    'One trunk past the third row wears a scar the wrong color, grey bark weeping a line gone hard and amber-dark. The hand pauses on it before the eye has decided why.',
  lacquerHint2:
    'The axe knows before the arm does — that grey trunk takes the blade soft, and the cut beads at once with a slow milk that stiffens on the steel. This is no firewood tree.',
  lacquerFound:
    "The nose knew it first, then the palm, and last the word: urushi. A lacquer tree, hidden all this time among the common pine, and the beading sap already worth more than the day's whole stack.",
  estateStands:
    'Let it be entered plainly, for whoever keeps these books hereafter: the estate stands. Every line above this one was the building of it.',
  nodeWeirRiverbankBlurb:
    "Matsuzō's weir, leased; the screens across it are the house's to keep whole. The river runs loud over the sill and flat below it. This is where they pulled you out.",
  nodeWeirRiverbankWrong:
    'Someone leaves offerings at the weir-jizō — a pinch of rice, set straight; once, a flower. No one at the house owns to it, and no one asks whose they are.',
  nodeGateGateyardBlurb:
    "The estate's face, kept barely: gateposts sound, paint long gone, the ground swept clean all the same. On market days Yohei's stall sets up inside the posts — the market comes to the house now.",
  nodeGateGateyardWrong:
    'The crest board over the gate is new wood on old posts. Where the old board went is not discussed.',
  nodeForecourtBlurb:
    "The outer court of the guest house, where the day's work is set out and seen to. Genemon's window looks onto it; what is done here gets written down.",
  nodeForecourtWrong:
    "Raked corner to corner, the court takes the whole morning. It was laid out for five households' worth of feet, and gets one.",
  nodeWoodshedBlurb:
    "A lean space between the woodpiles: a mat, a chipped bowl, a nail for the coat. It is not much, and it is not anyone else's.",
  nodeKitchenThresholdBlurb:
    'Meals are taken at the threshold, on the outer side of the sill. Within is the board, where terms are stated and portions decided, and where the household talks over you as if the sill were a wall.',
  nodeKitchenThresholdWrong:
    "The steward's papers share a shelf with the pickle crocks, and nobody carries them anywhere better.",
  nodeKuraBlurb:
    "The working storehouse: rice in, counted; rice out, counted again. The iron-strapped door and its good lock are the newest work on the estate. The grain-watch's post is a stool beside the door.",
  nodeKuraWrong:
    "The seal-plate above the door carries the house crest — count the petals, and it carries one more than the gate's. Nobody reads it aloud.",
  nodeDrillYardBlurb:
    "The old stable court, swept bare and given a new use. Kihei's ground: things happen here in his order or not at all.",
  nodeDrillYardWrong:
    'Stalls for twenty horses run the long side of the yard. The house owns one mule.',
  nodeHomePaddyBlurb:
    "The guest house's skirts: paddy water, vegetable rows, the plainest work there is — mud, water, backs. Everything else on the estate is paid for from here.",
  nodeHomePaddyWrong:
    "Out past the last worked row, the boundary stones stand in long grass. They are the house's. So is everything between.",
  nodeWoodlotEdgeBlurb:
    'Kindling and forage country past the last fence. No one works out here beside you; a hundred paces in, the sound of the estate stops.',
  nodeWoodlotEdgeWrong:
    'Some of the old stumps carry char. No one at the house puts a year to the burn.',
  nodeShrineCorridorBlurb:
    'A family altar set into a corridor — the rites kept properly in a passage never meant to hold them. You see it in passing. You are not asked to stop.',
  nodeShrineCorridorWrong:
    "Among the rites, the kind kept for the dead: a pair of straw travel-sandals, toes pointed away from the house. The straw is this year's.",
  nodeSickroomBlurb:
    'A lean-to surgery off the outer court: drawers of herbs, a pallet, the smell of moxa. You woke here first.',
  nodeSickroomWrong:
    'Sōan writes while you heal. Whatever the ledger holds, it is closed by the time the door finishes opening.',
  nodeRuinedCompoundBlurb:
    "Beyond a rope and a written warning: roofs fallen in on themselves, a great gate down across its own step, walls quarried low by the village, stone by stone. The house calls all of it the waste ground, and no one's eyes stay on it while they say so.",
  nodeRuinedCompoundWrong:
    'Whatever this was, it was no outbuilding. Nobody says what it was. Nobody says anything.',
  nodeOvergrownOrchardBlurb:
    "The old orchard gone wild: bramble to the shoulder, windfall rotting underfoot, dogs denned in the hollow — lean winters have made them bold. Kihei calls it the dogs' yard, without irony.",
  nodeOvergrownOrchardWrong:
    'Under the bramble the fruit trees stand in courtyard rows, planted by someone who expected paths between them, and lanterns.',
  nodeBambooGroveBlurb:
    'Green dark and creaking, close behind the waste ground. The monkey troop raids the vegetable rows from here and is gone up the stems before you have turned around. Shinnosuke is forbidden the grove, and is in the grove.',
  nodeBambooGroveWrong:
    'A waymark of cut bamboo stands at the path-fork, green — renewed this season, as it was last. No one claims the habit, and the habit is old.',
  nodeNightRoundsBlurb:
    "The round begins at the gate post: a stave, a hooded lamp, the order of the walk in Kihei's hand. Walk it clean and the house sleeps. Fall, and you wake at Sōan's.",
  nodeWeirReedsBlurb:
    'The shallows above and below the weir, reeds past the waist. River rats gnaw the screens the house leases from Matsuzō; every screen lost is coin owed. He counts the damage from his own bank, and does not raise his voice.',
  nodeWeirReedsWrong:
    'The gnawed screens are always the upstream ones. Whatever is feeding the rats, it is feeding them from above the weir.',
  nodeFieldMarginsBlurb:
    "Setts at the paddy's edge — tanuki, badger — and raids on the drying racks and the seed store. By the stories a tanuki is anything it wants to be; the one at the racks is a fat animal with its face in the seed rice.",
  nodeFieldMarginsWrong:
    "Dig far enough into the oldest sett and it bends toward the waste ground's wall — and goes under.",
  seasonWinter1:
    'Snow off the ridge by morning. The mule stays in; the well-rope stiffens overnight and has to be worked soft before the first bucket comes up.',
  seasonWinter2:
    'The village kilns are lit — char-smoke standing straight up the valley on the still days. Kindling fetches what firewood did in autumn.',
  seasonNewyear1:
    'Pine at every gate in the village, they say. The house sets one small pair at its own, and Genemon enters the cost.',
  seasonNewyear2:
    "First market of the year: Yohei's stall half stock, half talk. Prices rest a while; nobody haggles in the first week.",
  seasonSpring1:
    'The river comes up brown with the thaw and the weir takes the worst of it. Matsuzō walks his bank twice a day and says nothing yet.',
  seasonSpring2:
    'Seed rice out of the kura, counted twice. The paddies want water, the rows want hands, and the day is suddenly short.',
  seasonSummer1:
    'Heat by mid-morning. Work moves to the field edges and the shade of the kura wall; the monkeys move with it.',
  seasonSummer2:
    "A wedding at the miller's, two days gone. The kitchen heard when the red rice arrived — a bowl of it, already cool.",
  seasonBon1: 'Bon. The village road carries more people in a day than the gate sees in a season.',
  seasonBon2: "Yohei doesn't come Bon week. Even trade goes home.",
  seasonAutumn1:
    'Cutting weather, while it holds. Every field in the valley is a count now — sheaves, racks, and what the racks lose in the night.',
  seasonAutumn2:
    'The rice is in and the whole valley counts the same sky. Talk at the stall is all of the assessment; the talk stops when it arrives.',
  weatherRain:
    "Rain since first light. The yard's work waits under the eaves; the woodshed roof holds, this year.",
  weatherWind:
    'A wind off the mountain all day. The bamboo grove talks through it, and the gate-board knocks until someone wedges it.',
  weatherFog:
    "Fog up from the river till mid-morning. Matsuzō's bank is an outline; the weir is a sound.",
  weatherFrost:
    'First frost on the boundary stones. The far ones wear it longest, out where nobody works.',
  weatherDry:
    "A dry spell. The vegetable rows drink the well low, and hauling water climbs to the top of the day's list.",
  weatherThunder:
    'Thunder over the ridge at dusk, rain elsewhere. The paddies wanted it and did not get it.',
  marketStallUp:
    "Market day. Yohei's stall is up at first light — thread, salt, straw sandals, and one iron pot he swears he is losing money on.",
  marketThreadUp: 'Thread is a mon dearer at the stall. Yohei blames the road.',
  marketStrawCoat:
    "One straw coat on the stall — winter's whole stock. Yohei names its price without being asked.",
  marketNeedles:
    "Salt held its price; needles didn't. O-Hisa sends for two anyway and counts them into the sewing box like coin.",
  marketYoheiBuys:
    'Yohei buys today as well as sells: hides, clean bamboo, dried plums if anyone has them. His purse is a market-day purse — it empties.',
  marketNoStall:
    'No stall this week — the ford was up, and Yohei with a cartload on the far side of it. The gateyard is quieter than a market day should be.',
  gossipBirth:
    "O-Yae brings it with the fish: a boy born at the ferry keeper's, loud and early. The village has already decided who he looks like.",
  gossipLowlandWages:
    'They say the lowland wages are up again; two village boys have gone to try them. Their fields will be a pair of hands short at harvest, and everyone knows whose.',
  gossipFuneral:
    'A funeral over the ridge — an old man nobody here knew well. The village went anyway; the village always goes.',
  gossipRiverMan:
    'The village has it, by way of O-Yae, that the house keeps a man the river left. Some say lucky, some say the other thing. She reports both and owns neither.',
  gossipMatchmaker:
    "The matchmaker was at the headman's two days running. Nobody is saying whose name is on the table, which is how everyone knows it is serious.",
  gossipTownRice:
    'Word off the post road, third-hand by the time it reaches the board: rice is dear in the towns this year. Genemon writes something down.',
  gossipWeddingMissed:
    "Married out to the next valley: a charcoal-burner's daughter, in the house's harvest weeks. The news and the wedding sweets arrived a week apart, both a little stale.",
  gossipGanzo:
    "Ganzō at the well has the year of the great snow wrong again, they say, and will not be told. He was there; you weren't; that settles it.",
  questWeirRatsOffer:
    'River rats are at the leased screens again. Every slat gnawed through is coin owed across the water, and the day-book counts it whether anyone fights or not.',
  questWeirRatsComplete: 'The screens stand mended, slat by slat.',
  questWeirRatsReward:
    "Rat hides — stiff little things, but Yohei buys them by the bundle. The lease's damage line stays empty this season.",
  questWeirRatsSpeech: 'Matsuzō: "Water\'s running clean."',
  questGroveMonkeysOffer:
    "The troop is in the vegetable rows again — seed, eggs, whatever lifts. What the rows lose, the board feels by week's end.",
  questGroveMonkeysComplete:
    "The troop breaks for the grove with the big male going last, unhurried, carrying nothing. The rows are the house's again.",
  questGroveMonkeysReward:
    "A monkey-dropped sack, recovered: seed-corn, half of it still good, and one of the kitchen's missing eggs, unbroken. O-Hisa takes the count without comment.",
  questGroveMaleComplete:
    "The big male is the last to go, unhurried, and does not look back. The grove is quiet for a season's worth of nights.",
  questOrchardDogsOffer:
    "The old orchard is the dogs' yard, and the dogs have been bold since the lean winter. The fruit rots on the wild rows while the kitchen buys plums.",
  questOrchardDogsComplete:
    'The dens stand empty. What is left is work: wild rows to cut back, sound trees to find under the choke — the orchard becoming an orchard again.',
  questOrchardReclaimReward:
    'First fruit off the cleared rows — wind-fallen, wasp-bitten at the edges, and the kitchen takes every one. The day-book opens a line it has not carried in years: orchard.',
  questMarginSettsOffer:
    'The racks lose more each night — tanuki at the drying frames, a badger under the seed store. Harvest is a count, and the count is going backward.',
  questMarginSettsComplete:
    "The setts at the field margin are dug out and collapsed. O-Ume's plot borders the worst of it; she thanks the kami for the quiet, and means it.",
  questMarginSettsReward:
    "Hides for the stall, and the seed store's floor swept clean. Under the badger's sett, the thieved hoard: a winter of small theft, recovered in one dig.",
  questNightRoundOffer:
    'Kihei has drawn the night round: gate to kura to weir and back, every dark hour accounted for. The first round is walked together; after that, the post is at the gate.',
  questNightRoundSpeech: 'Kihei: "Walk it once with me. Then it\'s yours."',
  questNightRoundComplete:
    'The round comes back to the gate with nothing to report, which is what a round is for.',
  questNightRoundReward:
    'The round-board hangs by the gate post now — a plain slat with the route burned in. Whoever walks the round turns it; whoever passes can see it turned.',
  questTurnInSpeech: 'Genemon: "Entered."',
  perkWhetstone:
    'Ten strokes on the stone each dawn, angle held shallow, both sides evened. The sickle bites all day on one honing.',
  perkCarryingKnot:
    'A hitch that tightens under load and gives one-handed. Nothing roped with it shifts on the road, and nothing has to be tied twice.',
  perkWatchPost:
    "Where to stand at the gate after dark: back to the lamp, face to the dark, where the yard's three paths meet in one eye-line. From there, nothing crosses unseen.",
  perkWeirSlats:
    'How a weir screen goes together: green bamboo split with the grain, lashed wet so it tightens as it dries. A screen mended this way outlasts a bought one.',
  perkOakStave:
    'A stave cut to the hand that holds it: where to grip, how to stand, when not to swing. Ten motions, every dawn, in the same order.',
  perkSecondCount:
    'Count the coins into the palm, then out of it. Two counts, one answer, before the purse closes. Yohei counts fast; the second count is yours.',
  perkRatRuns:
    'Rats keep to their lines — wall edges, sill gaps, the dark side of the grain bales. Know the lines, and the watch is half stood before dark.',
  perkForageBasket:
    "The woodlot's give, learned path by path: which mushrooms are dinner and which are a night in Sōan's sickroom, where the good kindling falls, what each season puts out and where it hides it.",
  mobRatStore:
    'Comes for the grain along the wall lines after dark, night on night, by the measure. Bar the kura door low as well as high; a rat does not need much of a gap, and never needs it twice.',
  mobRatRiver:
    'Gnaws the leased screens at the waterline and dens in the reed bank. Wade the shallows at dusk with a stick and a sack; the work is wet and the count is honest.',
  mobTanuki:
    'Fat by autumn, boldest at the drying racks. The stories give it ten shapes; by daylight it has one — round, low, and gone at a shout. Dig the sett, or lose the racks nightly.',
  mobBadger:
    'Digs where the ground is soft and the seed is near. Slow to rouse and hard to stop once roused — never put a bare hand down the sett. It leaves when the digging costs it more than the seed pays.',
  mobMonkey:
    'Raids the rows in company, posts a watcher, carries off whatever lifts. Boldest in summer and through Bon. Drive off the whole troop at once, or the rest drift back by morning — they count you, too.',
  mobMonkeyMale:
    'Head of the grove troop, half again the size of the rest and unafraid of a stick. He goes over the wall last, at his own pace. If he has not moved, the troop has not moved.',
  mobFeralDog:
    "Dens in the old orchard; bolder in winter, boldest in a pack. It was somebody's dog once, or its sire was — it knows what a man is. Never run. Break the pack, and what is left is only dogs.",
  mobMarten:
    'Comes over the roof, not the wall, and kills more than it carries. The sign is the smell, and a small clean ruin where the coop was in order. Night work — take a light.',
  mobWolf:
    'Comes down in a lean winter, alone, after the rats and the smell of stored grain. Big track, no sound, no waste. Do not stand a watch against a wolf without a fire at your back.',
  mobMamushi:
    'Patterned like dead leaves, thick for its length, short-tempered in the warm months; it holds its ground in the grass where a foot is about to land. The rat-snake is long, plain, and earns its keep in the kura — leave that one be. Know the two apart before the grass is high.',
  nightRoundPost:
    'The watch post is a stool, a hooded lantern, and the boar-spear leaning where Kihei left it. The round begins when you lift the lantern, and ends when you set it down here again.',
  nightRoundRats:
    'Rats in the store, where Kihei said. You learn the sound grain makes when something small is stealing it — a dry whisper under the floor, gone the moment you stop walking. The spear-butt does the rest. In the morning you sweep up what they spoiled and say what you took. The number is never nothing.',
  nightRoundMarten:
    'A marten, quick as spilled water, dead by more luck than spear-work. Behind the back bales, where it hunted, you find what the rats had all along — a seed-rice bale gnawed open at the seam, half gone into the walls. You make the count alone, by lantern, twice. It does not improve the second time. You bar the door on it and tell no one yet.',
  nightRoundWolf:
    'At the kura door the lantern finds two eyes at the height of your waist, and the dark around them is the wrong shape for a dog. The bar is behind you. So is the rice.',
  nightRoundNewMoon:
    "On the dark of the moon a lantern crosses the far edge of the yard — hooded low, held steady, going upstream. By the time the round brings you back the yard is empty, and in the morning no one has missed a lantern. It is not your watch's business. You watch for it anyway.",
  nightRoundFall:
    "You wake on Sōan's mat with daylight standing in the wrong place. Days gone, and the wages with them. He asks one question, writes two lines, and closes the ledger when you turn your head.",
  reedsHint0:
    'The reeds above the sill hold whatever the river gives up, and the work has never yet left time to go through them.',
  reedsHint1:
    'Mending the third screen, the pole snags in the reed roots on something that gives like cloth, not like root.',
  reedsHint2:
    "At low water a corner of dark cloth shows wedged in the reed roots off the third screen, silted to their color, an arm's reach down.",
  reedsFound:
    'Out of the reeds, a bundle: river-heavy, the cloth gone the color of the bank, tied off in a knot your hands undo without being told. Inside, wrapped twice against the wet, a single paper — the ink run to gray, not one word of it left.',
  sluiceHint0:
    'However the ditches are kept, the far paddies take their water last, and take it thin.',
  sluiceHint1:
    'The feed ditch goes in under the woodlot trees carrying more water than ever comes out the other side.',
  sluiceHint2:
    'At the woodlot edge the ditch ends against a bank of silt, and square-cut stone shows through where the rain has worked it.',
  sluiceFound:
    'Under the silt, cut stone and a lift-board seized in its groove: a sluice-gate, made well and left to choke. Clearing it is days of honest digging, and nobody at the house knows it is there to clear.',
  settHint0:
    'The racks nearest the old compound wall lose the most, season after season, whatever watch is set.',
  settHint1:
    'Cut off one run and the badger cuts another, and every one of them bears toward the foot of the old wall.',
  settHint2:
    "Behind the scrub at the wall's foot the ground is worked hollow, fresh earth thrown out from under the stones themselves.",
  settFound:
    "At the wall's foot the spade finds the sett's main gallery: old work, wider than the badger needs, going down under the stones and not coming up on this side. The digging stops at the stones.",
  judgeLineFail:
    "On the village road the house's name is said in the low voice kept for endings. Nobody wishes it ill; the valley is only deciding, early, what its fields will come to.",
  judgeLineBad:
    "The house's word is worth less down the valley than it was: at the stall its name still buys, but the amounts are counted slowly.",
  judgeLineOk:
    'The valley lets the house be — greeted on the road, owed nothing, promised nothing. This year, being left alone is a kind of standing.',
  judgeLineGood:
    "Word goes down the valley ahead of the season's close: the gate is kept, the roofs hold, and the house's name is said plainly again, without the pause that used to follow it.",
  judgeLineGreat:
    'The road bends toward the gate again — a favor asked of the house, a cart that slows without needing anything. The valley has resumed expecting things of it.',
  judgeLineExcellent:
    'The season closes on a house the valley measures by once more: its name given first in any accounting of names, as it was given in years nobody thought would come back.',
} as const;
