// GENERATED by `pnpm run gen:narrative` from src/core/content/narrative/intro.md — DO NOT EDIT.
// Hand edits here are drift by definition: edit the markdown source and regenerate
// (the gen-narrative verify gate rebuilds this file and byte-compares it).
// Data only — the types + helpers stay hand-written in intro.ts, which re-exports this.

import { COLD_OPEN } from './coldOpen';
import { getDialogueLine } from './dialogue';
import { NAMES } from './names';
import { NPC_NAME } from './voices';
import type { DialogueScene } from './intro';

export const DIALOGUE_SCENES: readonly DialogueScene[] = [
  {
    id: 'dream',
    voice: 'narrator',
    greeting: [{ voice: 'narrator', text: COLD_OPEN.dream }],
    topics: [],
    decision: {
      prompt: 'The fragment tugs. Do you follow it?',
      options: [
        {
          id: 'dream-dwell',
          label: 'Dwell on it',
          say: '"Hold the road. The rain. Almost a name."',
          react:
            'You chase it inward — and the ache in your skull chases you back. The name stays lost, but the habit of looking sets in.',
          stat: { up: 'int', down: 'spd' },
          perk: {
            name: 'The Inward Turn',
            desc: 'A mind that deepens by dwelling, at the price of a slower body.',
          },
        },
        {
          id: 'dream-shake',
          label: 'Shake it off',
          say: '"Later. The body is here; the past isn\'t."',
          react: 'You let it go and the room sharpens — the slats of light, the way out.',
          stat: { up: 'spd', down: 'int' },
          perk: {
            name: 'The Clear Room',
            desc: 'Senses sharpened to the way out — quick where thought is thin.',
          },
        },
        {
          id: 'dream-hands',
          label: 'Trust the hands',
          say: '"A porter\'s knot. My hands know this much."',
          react:
            "Your fingers move before you decide to — a labourer's memory, still in the muscle.",
          stat: { up: 'str', down: 'luck' },
          perk: {
            name: "The Porter's Hands",
            desc: 'Hands that remember the work before the head does.',
          },
        },
      ],
    },
  },

  {
    id: 'soan',
    voice: 'physician',
    speaker: 'soan',
    greeting: [
      { voice: 'narrator', text: COLD_OPEN.weir },
      { voice: 'narrator', text: COLD_OPEN.wake },
      {
        voice: 'narrator',
        text: 'The physician does not ask how you feel. He takes your wrist, then your jaw, then turns your hands over and looks at them longer than at anything else. He presses a thumb into the callus line across one palm and says nothing. There is a ledger open on his knee.',
      },
      { voice: 'physician', speaker: NPC_NAME.soan, text: '"Do you know the year?"' },
      { voice: 'player', text: '"No."' },
      {
        voice: 'physician',
        speaker: NPC_NAME.soan,
        text: '"An\'ei nine. Now you know it again. Drink this."',
      },
      {
        voice: 'narrator',
        text: 'Whatever the hands told him goes into the ledger, two lines, too far off to read. The door slides, and he closes the book on his thumb.',
      },
      {
        voice: 'narrator',
        text: 'The man in the doorway is grey and dry and carries a book of his own. Two books in the room now, and only one of them open.',
      },
      { voice: 'steward', speaker: NPC_NAME.genemon, text: '"The weir man. Sōan — can he work?"' },
      { voice: 'physician', speaker: NPC_NAME.soan, text: '"Ask him."' },
      {
        voice: 'steward',
        speaker: NPC_NAME.genemon,
        text: '"Name, age, where from. In that order."',
      },
      {
        voice: 'narrator',
        text: 'Three answers, and you do not have one of them. The silence goes on long enough that the physician looks up.',
      },
      { voice: 'player', text: '"What name did I give? When they pulled me out."' },
      {
        voice: 'physician',
        speaker: NPC_NAME.soan,
        text: '"None. You gave none. Three days I have had nothing to call you, and neither have you."',
      },
      { voice: 'narrator', text: 'Nothing comes.' },
      {
        voice: 'narrator',
        text: 'Genemon does not look surprised. He looks down and writes, and reads it back as he writes, aloud and once.',
      },
      { voice: 'steward', speaker: NPC_NAME.genemon, text: COLD_OPEN.daybook },
      {
        voice: 'steward',
        speaker: NPC_NAME.genemon,
        text: '"When he can stand, he rakes. The kitchen wants water before it wants anything."',
      },
      {
        voice: 'narrator',
        text: 'He goes. Sōan opens his ledger again, where his thumb kept the place.',
      },
    ],
    topics: [
      {
        id: 'soan-where',
        label: '"Where is this?"',
        answer: [
          {
            voice: 'physician',
            speaker: NPC_NAME.soan,
            text: `"The ${NAMES.house} house — the estate, or what answers to the word. This is my sickroom, off the outer court, and you will be out of it by tomorrow. I need the mat."`,
          },
        ],
      },
      {
        id: 'soan-kami',
        label: '"Someone on the bank said a god hid me."',
        answer: [
          {
            voice: 'physician',
            speaker: NPC_NAME.soan,
            text: '"Kamikakushi. The valley says it of every man the river takes and every child who runs off. Let them say it; it comforts them and costs you nothing. What took you was water."',
          },
        ],
      },
      {
        id: 'soan-how-long',
        label: '"How long was I in the river?"',
        answer: [
          {
            voice: 'physician',
            speaker: NPC_NAME.soan,
            text: '"That I can\'t write down. Three days here, fevered. Before that, ask the river."',
          },
        ],
      },
    ],
    decision: {
      prompt: 'No name, then. What do you keep instead?',
      options: [
        {
          id: 'soan-knot',
          label: '"My hands know a knot. I\'ll keep that."',
          say: '"My hands know a knot. I\'ll keep that."',
          react:
            "You tie it in the cord of your own bedding: a carrier's hitch, fast and one-handed, twice. Sōan watches it both times. He does not write it down while you are looking.",
          stat: { up: 'agi', down: 'int' },
          perk: { name: "The Carrier's Hitch", desc: 'fast, one-handed, holds wet.' },
          memory: { npc: 'soan', regard: 'noted', warmth: 1 },
        },
        {
          id: 'soan-work',
          label: '"The work. Point me at it."',
          say: '"The work. Point me at it."',
          react:
            '"Can you stand? Then the rake is by the door, and the well is past the kitchen. Water first — the kitchen never has enough. Come back when something bleeds."',
          stat: { up: 'str', down: 'luck' },
          perk: { name: 'The Well Yoke', desc: 'a load the shoulders carry before it is asked.' },
          memory: { npc: 'soan', regard: 'plain', warmth: 0 },
        },
        {
          id: 'soan-count',
          label: '"The days. I\'ll count from this one."',
          say: '"The days. I\'ll count from this one."',
          react:
            '"Day four, by mine. Yours can start where you like. Mark the post — notches hold."',
          stat: { up: 'int', down: 'agi' },
          perk: { name: 'The Notched Post', desc: 'a day cut where fever cannot blur it.' },
          memory: { npc: 'soan', regard: 'methodical', warmth: 0 },
        },
      ],
    },
  },

  {
    id: 'genemon',
    voice: 'steward',
    speaker: 'genemon',
    greeting: [
      {
        voice: 'steward',
        speaker: NPC_NAME.genemon,
        text: getDialogueLine('genemon-open', 'gen-greet').text,
      },
    ],
    topics: [
      {
        id: 'gen-house',
        label: '"What house is this?"',
        answer: [
          {
            voice: 'steward',
            speaker: NPC_NAME.genemon,
            text: `"The ${NAMES.house}. A great name gone to seed — samurai on the rolls, paupers in the granary. I've kept it upright since the last master could not, and I'll keep it upright when you can't either."`,
          },
        ],
      },
      {
        id: 'gen-work',
        label: '"What work is there?"',
        answer: [
          {
            voice: 'steward',
            speaker: NPC_NAME.genemon,
            text: '"Rice to rake, a paddy to tend, a storehouse standing half-empty. Honest labour and no shortage of it. Earn your keep and there\'s a dry corner and a bowl in it — that\'s the whole of what I can promise."',
          },
        ],
      },
      {
        id: 'gen-you',
        label: '"And who are you to me?"',
        answer: [
          {
            voice: 'steward',
            speaker: NPC_NAME.genemon,
            text: "\"Steward. I run the estate; you'll learn it, or you won't eat. Do as I say on the house's matters and we'll get on well enough.\"",
          },
        ],
      },
      {
        id: 'gen-danger',
        label: '"Is it safe here?"',
        gate: (asked) => asked.has('gen-work'),
        answer: [
          {
            voice: 'steward',
            speaker: NPC_NAME.genemon,
            text: "\"Safe as anywhere the lord's men don't ride. There's a wolf gone bold at the grain store, and worse up in the hills. But that's tomorrow's trouble. Today it's rice.\"",
          },
        ],
      },
    ],
    decision: {
      prompt: 'How do you answer the steward?',
      options: [
        {
          id: 'genemon-earnest',
          label: 'Earnest — point me at the work',
          say: '"I\'ll earn my keep. Point me at it."',
          react:
            '"...Good. The house has had its fill of hands that don\'t. We\'ll see if you mean it."',
          stat: { up: 'str', down: 'agi' },
          perk: {
            name: `${NAMES.elder}'s Charge`,
            desc: 'Honest muscle set plainly to the task — sure over nimble.',
          },
          memory: { npc: 'genemon', regard: 'earnest', warmth: 1 },
        },
        {
          id: 'genemon-wary',
          label: "Wary — what's in it for me",
          say: '"A samurai house with an empty granary. What\'s in it for me?"',
          react:
            '"An honest question, and a cold one. Rice and a dry corner — that\'s the whole of what I can promise. Take it or walk."',
          stat: { up: 'agi', down: 'str' },
          perk: {
            name: 'The Wary Foot',
            desc: 'A guard kept up and light on the feet — quick to move before committing.',
          },
          memory: { npc: 'genemon', regard: 'wary', warmth: -1 },
        },
        {
          id: 'genemon-steady',
          label: 'Silent — just get to work',
          say: '(You say nothing, and reach for the spilled rice.)',
          react: '"...A man who works before he talks. Rare. We\'ll get on."',
          stat: { up: 'spd', down: 'luck' },
          perk: {
            name: 'Hands Before Words',
            desc: 'A steady quickness that answers with work — trusting to no luck.',
          },
          memory: { npc: 'genemon', regard: 'steady', warmth: 1 },
        },
      ],
    },
  },
];
