// GENERATED by `npm run gen:narrative` from src/core/content/narrative/intro.md — DO NOT EDIT.
// Hand edits here are drift by definition: edit the markdown source and regenerate
// (the gen-narrative verify gate rebuilds this file and byte-compares it).
// Data only — the types + helpers stay hand-written in intro.ts, which re-exports this.

import { COLD_OPEN } from './coldOpen';
import { getDialogueLine } from './dialogue';
import { NAMES } from './names';
import { NPC_NAME } from './voices';
import type { DialogueScene } from './intro';

export const DIALOGUE_SCENES: readonly DialogueScene[] = [
  {
    id: 'soan',
    voice: 'physician',
    speaker: 'soan',
    greeting: [
      { voice: 'narrator', text: COLD_OPEN.wake },
      { voice: 'physician', speaker: NPC_NAME.soan, text: COLD_OPEN.grounding },
    ],
    topics: [
      {
        id: 'soan-what-happened',
        label: '"What happened to me?"',
        answer: [
          {
            voice: 'physician',
            speaker: NPC_NAME.soan,
            text: '"You washed up below the weir three days back, a gash on your scalp and no name to give. The river does that. We fished you out; the rest you\'ll have to earn back."',
          },
        ],
      },
      {
        id: 'soan-kami',
        label: '"The village says a kami hid me away."',
        answer: [
          {
            voice: 'physician',
            speaker: NPC_NAME.soan,
            text: "\"Kami-kakushi — 'spirited away.' It's the tale they tell for every soul that wanders off and every child the river takes. I've tended enough of the 'spirited-away' to know it's water and cold and bad luck, not spirits. Don't let the old women make a haunting of it.\"",
          },
        ],
      },
      {
        id: 'soan-fragment',
        label: '"There\'s a road. Grey rain. A name I can\'t hold."',
        answer: [
          {
            voice: 'physician',
            speaker: NPC_NAME.soan,
            text: '"That\'s the blow talking, not a ghost. Fragments surface as the swelling goes down — chase them if you must, but a name you have to dig for is rarely one worth keeping."',
          },
        ],
      },
      {
        id: 'soan-mend',
        label: '"How do I get my strength back?"',
        answer: [
          {
            voice: 'physician',
            speaker: NPC_NAME.soan,
            text: '"Rest, rice, and work — in that order at first, then all at once. The body remembers labour before the mind remembers anything. The wits come back last; don\'t force them."',
          },
        ],
      },
    ],
    decision: {
      prompt: 'What do you say to him?',
      options: [
        {
          id: 'soan-grateful',
          label: 'Thank him — ask how to mend',
          say: '"Then I\'ll trust your craft, not the village\'s ghosts."',
          react:
            '"Sense, at last. Rest, eat, and let the swelling go down. The wits come back last — don\'t force them."',
          stat: { up: 'int', down: 'str' },
          perk: {
            name: `${NAMES.physician}'s Counsel`,
            desc: 'A mind honed sharper than the body it wears.',
          },
          memory: { npc: 'soan', regard: 'grateful', warmth: 1 },
        },
        {
          id: 'soan-curt',
          label: 'Brush it off — ask for work',
          say: '"Kami or flood, I\'m still breathing. Where\'s the work?"',
          react:
            '"...Hm. No patience for a physician. Well — the body heals the same whether you thank me or not."',
          stat: { up: 'str', down: 'int' },
          perk: {
            name: 'Sickbed Grit',
            desc: 'A back that shoulders the work before the wits can weigh in.',
          },
          memory: { npc: 'soan', regard: 'curt', warmth: -1 },
        },
        {
          id: 'soan-worried',
          label: 'Grasp at the fragment',
          say: '"There was a road. Grey rain. A name I can\'t hold. Is that the fever?"',
          react:
            '"That is the blow talking, not a ghost. It will fade — or it won\'t. Don\'t let the old women make a haunting of it."',
          stat: { up: 'luck', down: 'agi' },
          perk: {
            name: 'A Waking Fragment',
            desc: 'A half-caught omen that bends fortune your way, though your step is slower to answer.',
          },
          memory: { npc: 'soan', regard: 'worried', warmth: 0 },
        },
      ],
    },
  },

  {
    id: 'dream',
    voice: 'narrator',
    greeting: [{ voice: 'narrator', text: COLD_OPEN.dream }],
    topics: [],
    decision: {
      prompt: 'The fragment tugs. Do you follow it?',
      options: [
        {
          id: 'dream-dwell',
          label: 'Dwell on it',
          say: '"Hold the road. The rain. Almost a name."',
          react:
            'You chase it inward — and the ache in your skull chases you back. The name stays lost, but the habit of looking sets in.',
          stat: { up: 'int', down: 'spd' },
          perk: {
            name: 'The Inward Turn',
            desc: 'A mind that deepens by dwelling, at the price of a slower body.',
          },
        },
        {
          id: 'dream-shake',
          label: 'Shake it off',
          say: '"Later. The body is here; the past isn\'t."',
          react: 'You let it go and the room sharpens — the slats of light, the way out.',
          stat: { up: 'spd', down: 'int' },
          perk: {
            name: 'The Clear Room',
            desc: 'Senses sharpened to the way out — quick where thought is thin.',
          },
        },
        {
          id: 'dream-hands',
          label: 'Trust the hands',
          say: '"A porter\'s knot. My hands know this much."',
          react:
            "Your fingers move before you decide to — a labourer's memory, still in the muscle.",
          stat: { up: 'str', down: 'luck' },
          perk: {
            name: "The Porter's Hands",
            desc: 'Hands that remember the work before the head does.',
          },
        },
      ],
    },
  },

  {
    id: 'genemon',
    voice: 'steward',
    speaker: 'genemon',
    greeting: [
      {
        voice: 'steward',
        speaker: NPC_NAME.genemon,
        text: getDialogueLine('genemon-open', 'gen-greet').text,
      },
    ],
    topics: [
      {
        id: 'gen-house',
        label: '"What house is this?"',
        answer: [
          {
            voice: 'steward',
            speaker: NPC_NAME.genemon,
            text: `"The ${NAMES.house}. A great name gone to seed — samurai on the rolls, paupers in the granary. I've kept it upright since the last master could not, and I'll keep it upright when you can't either."`,
          },
        ],
      },
      {
        id: 'gen-work',
        label: '"What work is there?"',
        answer: [
          {
            voice: 'steward',
            speaker: NPC_NAME.genemon,
            text: '"Rice to rake, a paddy to tend, a storehouse standing half-empty. Honest labour and no shortage of it. Earn your keep and there\'s a dry corner and a bowl in it — that\'s the whole of what I can promise."',
          },
        ],
      },
      {
        id: 'gen-you',
        label: '"And who are you to me?"',
        answer: [
          {
            voice: 'steward',
            speaker: NPC_NAME.genemon,
            text: "\"Steward. I run the estate; you'll learn it, or you won't eat. Do as I say on the house's matters and we'll get on well enough.\"",
          },
        ],
      },
      {
        id: 'gen-danger',
        label: '"Is it safe here?"',
        gate: (asked) => asked.has('gen-work'),
        answer: [
          {
            voice: 'steward',
            speaker: NPC_NAME.genemon,
            text: "\"Safe as anywhere the lord's men don't ride. There's a wolf gone bold at the grain store, and worse up in the hills. But that's tomorrow's trouble. Today it's rice.\"",
          },
        ],
      },
    ],
    decision: {
      prompt: 'How do you answer the steward?',
      options: [
        {
          id: 'genemon-earnest',
          label: 'Earnest — point me at the work',
          say: '"I\'ll earn my keep. Point me at it."',
          react:
            '"...Good. The house has had its fill of hands that don\'t. We\'ll see if you mean it."',
          stat: { up: 'str', down: 'agi' },
          perk: {
            name: `${NAMES.elder}'s Charge`,
            desc: 'Honest muscle set plainly to the task — sure over nimble.',
          },
          memory: { npc: 'genemon', regard: 'earnest', warmth: 1 },
        },
        {
          id: 'genemon-wary',
          label: "Wary — what's in it for me",
          say: '"A samurai house with an empty granary. What\'s in it for me?"',
          react:
            '"An honest question, and a cold one. Rice and a dry corner — that\'s the whole of what I can promise. Take it or walk."',
          stat: { up: 'agi', down: 'str' },
          perk: {
            name: 'The Wary Foot',
            desc: 'A guard kept up and light on the feet — quick to move before committing.',
          },
          memory: { npc: 'genemon', regard: 'wary', warmth: -1 },
        },
        {
          id: 'genemon-steady',
          label: 'Silent — just get to work',
          say: '(You say nothing, and reach for the spilled rice.)',
          react: '"...A man who works before he talks. Rare. We\'ll get on."',
          stat: { up: 'spd', down: 'luck' },
          perk: {
            name: 'Hands Before Words',
            desc: 'A steady quickness that answers with work — trusting to no luck.',
          },
          memory: { npc: 'genemon', regard: 'steady', warmth: 1 },
        },
      ],
    },
  },
];
