// GENERATED by `pnpm run gen:narrative` from src/core/content/narrative/requirements.md — DO NOT EDIT.
// Hand edits here are drift by definition: edit the markdown source and regenerate
// (the gen-narrative verify gate rebuilds this file and byte-compares it).
// Data only — the types + helpers stay hand-written in requirements.ts, which re-exports this.

import type { RequirementDef } from '../requirements-engine';
import type { RankId } from './ranks';
import { NAMES } from './names';

export const RUNG_REQUIREMENTS: Readonly<Record<RankId, readonly RequirementDef[]>> = {
  R0: [
    {
      id: 'rake-the-first-rows',
      type: 'count',
      token: 'act:rake_rice',
      target: 10,
      flavor: `"So he can work," ${NAMES.elder} says, in the way another man says good morning.`,
      objective: 'The spill by the granary door lies raked into heaps.',
      drive: 'rake_rice',
    },
    {
      id: 'rake-through-the-night',
      type: 'count',
      token: 'act:rake_rice',
      target: 20,
      flavor: `"Still at it," ${NAMES.elder} says, passing the granary door without stopping.`,
      objective: 'Half the granary floor shows swept boards under the lamp.',
      drive: 'rake_rice',
    },
    {
      id: 'rake-the-spill',
      type: 'count',
      token: 'act:rake_rice',
      target: 35,
      flavor: `"Dawn, and he is still raking," ${NAMES.elder} says to the dark, as if the dark had asked.`,
      objective: 'At dawn the granary floor stands bare, wall to wall.',
      drive: 'rake_rice',
    },
  ],

  R1: [
    {
      id: 'first-rows-of-his-own',
      type: 'count',
      token: 'act:farm_paddy',
      target: 10,
      flavor: "The first rows he plants alone come up as straight as anyone's.",
      objective: 'The first rows set alone stand straight in the water.',
      drive: 'farm_paddy',
    },
    {
      id: 'take-to-the-fields',
      type: 'count',
      token: 'act:farm_paddy',
      target: 30,
      flavor: 'The paddy women no longer point out which rows are his; he has learned them.',
      objective: 'The paddy stands planted, not a row out of true.',
      drive: 'farm_paddy',
    },
    {
      id: 'a-porters-back',
      type: 'count',
      token: 'act:haul_stores',
      target: 25,
      flavor:
        'At the gate the porters shift a strap for him without being asked, as they do among their own.',
      objective: 'The carrying-pole is worn smooth where a new grip sits.',
      drive: 'haul_stores',
    },
  ],

  R2: [
    {
      id: 'learn-the-woodlot',
      type: 'count',
      token: 'act:woodcut_edge',
      target: 20,
      flavor:
        'The axe haft darkens where his grip has settled, and the stumps at the woodlot edge stand cut clean.',
      objective: 'Split wood is stacked head-high along the woodlot path.',
      drive: 'woodcut_edge',
    },
    {
      id: 'walk-the-hills',
      type: 'count',
      token: 'act:forage_satoyama',
      target: 25,
      flavor:
        'The near hills give up bracken and mushrooms without a search; the basket comes home heavy before noon.',
      objective: "The kitchen's drying racks are full of hill mushrooms.",
      drive: 'forage_satoyama',
    },
    {
      id: 'keep-the-stores-moving',
      type: 'count',
      token: 'act:haul_stores',
      target: 20,
      flavor:
        'Bales pass the gate and none sit long; the storehouse floor shows bare wood where sacks once rotted.',
      objective: 'No bale sits long enough at the gate to sour.',
      drive: 'haul_stores',
    },
  ],

  R3: [
    {
      id: 'clear-the-kura-rats',
      type: 'count',
      token: 'kill:river_rats',
      target: 3,
      flavor: `"Quiet in the kura tonight," ${NAMES.drillmaster} lets drop, cleaning his blade by lamplight.`,
      objective: 'The weir screens hold whole, no rat-run gnawed through them.',
      drive: 'fight river_rats',
    },
    {
      id: 'drive-off-the-thieves',
      type: 'count',
      token: 'kill:tanuki',
      target: 2,
      flavor: `"The monkeys have learned his shape," ${NAMES.drillmaster} is heard to say, almost pleased.`,
      objective: 'The tanuki runs at the field margins lie empty.',
      drive: 'fight tanuki',
    },
    {
      id: 'the-fields-hold',
      type: 'count',
      token: 'act:farm_paddy',
      target: 15,
      flavor: `"The fields don't miss him while he drills," ${NAMES.elder} notes, half to himself.`,
      objective: 'Not a paddy lies untended while the watch is kept.',
      drive: 'farm_paddy',
    },
    {
      id: 'keep-the-rows',
      type: 'count',
      token: 'act:farm_paddy',
      target: 30,
      flavor: `"Watch or no watch, his rows never fell behind," ${NAMES.elder} says over the evening rice.`,
      objective: 'The rows run green to the bund with no gap.',
      drive: 'farm_paddy',
    },
    {
      id: 'timber-for-the-palisade',
      type: 'count',
      token: 'act:woodcut_edge',
      target: 25,
      flavor: `"The palisade wood is his cutting," ${NAMES.drillmaster} says, striking a post with the flat of his hand.`,
      objective: 'New posts stand in the palisade, pale against the weathered wood.',
      drive: 'woodcut_edge',
    },
    {
      id: 'the-wolf-survived-not-won',
      type: 'flag',
      flag: 'wolf-survived-not-won',
      flavor:
        'The night the wolf came you stood between it and the stores, and were still there at dawn — bleeding, ribs cracked, the rice untouched. Not won. Survived.',
      objective: 'Blood on the granary step, and not a grain gone.',
      drive:
        'the R3 first night round resolves its scripted survive-not-won wolf stage, setting `wolf-survived-not-won`.',
    },
  ],

  R4: [
    {
      id: 'a-load-among-loads',
      type: 'count',
      token: 'act:haul_stores',
      target: 25,
      flavor: 'The porters have stopped counting his loads against their own.',
      objective: "The kura's floor is squared and roped, load by load.",
      drive: 'haul_stores',
    },
    {
      id: 'first-name-in-the-yard',
      type: 'count',
      token: 'act:haul_stores',
      target: 50,
      flavor: 'When the kura needs moving in a hurry, it is his name the yard calls first.',
      objective: "A kura's worth of bales moves between dawn and dusk.",
      drive: 'haul_stores',
    },
    {
      id: 'the-stores-know-you',
      type: 'count',
      token: 'act:haul_stores',
      target: 75,
      flavor: 'New porters are told to watch how he stacks; nobody remembers deciding that.',
      objective: 'Every stack in the kura leans the same way now.',
      drive: 'haul_stores',
    },
    {
      id: 'a-hundred-mon-held',
      type: 'state',
      pred: { kind: 'resource', res: 'coin', min: 100 },
      flavor:
        'The house learns he keeps coin of his own, strung and counted, spent on nothing foolish.',
      objective: 'A hundred mon, strung and hidden in the north corner.',
      drive: 'sell rice',
    },
  ],

  R5: [
    {
      id: 'first-deep-baskets',
      type: 'count',
      token: 'act:forage_deepwoods',
      target: 10,
      flavor:
        'The first deep-hill baskets come back full, and no one mentions the danger line twice.',
      objective: 'Deep-hill baskets stand full at the kitchen door.',
      drive: 'forage_deepwoods',
    },
    {
      id: 'past-the-danger-line',
      type: 'count',
      token: 'act:forage_deepwoods',
      target: 25,
      flavor:
        "He comes back from past the charcoal-burners' marker so often the kitchen stops waiting up.",
      objective: "The path past the charcoal-burners' marker is beaten flat now.",
      drive: 'forage_deepwoods',
    },
    {
      id: 'the-paddies-still-first',
      type: 'count',
      token: 'act:farm_paddy',
      target: 25,
      flavor: `Whatever else he is now, the paddies get his mornings first, and ${NAMES.elder} sees that they do.`,
      objective: 'No morning passes with the paddies left to wait.',
      drive: 'farm_paddy',
    },
    {
      id: 'a-made-corner',
      type: 'state',
      pred: { kind: 'belonging', id: 'bedding' },
      flavor:
        'There is bedding in the north corner, bought with his own coin, and the maids sweep around it now.',
      objective: 'There is bedding in the north corner that no one moves.',
      drive: 'buy bedding',
    },
  ],

  R6: [
    {
      id: 'the-count-comes-early',
      type: 'count',
      token: 'act:haul_stores',
      target: 25,
      flavor: `"The store-room count is early this month," ${NAMES.steward} says, not yet naming why.`,
      objective: 'The store-room is empty of unshifted bales by mid-month.',
      drive: 'haul_stores',
    },
    {
      id: 'the-ledgers-agree',
      type: 'count',
      token: 'act:haul_stores',
      target: 65,
      flavor: `"The ledgers agree tonight," ${NAMES.steward} says, which is her whole praise.`,
      objective: 'No sack goes missing between the gate and the kura.',
      drive: 'haul_stores',
    },
    {
      id: 'three-hundred-mon-steady',
      type: 'state',
      pred: { kind: 'resource', res: 'coin', min: 300 },
      flavor: `"His purse holds steady," ${NAMES.steward} lets fall, "which is more than this house has managed."`,
      objective: 'Three hundred mon sit strung under the floorboard, none spent.',
      drive: 'sell rice',
    },
    {
      id: 'coin-into-the-works',
      type: 'state',
      pred: { kind: 'native', key: 'estate-u1' },
      flavor: `"He put his own coin into the kura-works," ${NAMES.steward} tells ${NAMES.elder}, twice, to be sure he heard.`,
      objective: 'The kura-works stand mended with timber no lord paid for.',
      drive: 'buy estate_upgrade',
    },
  ],

  R7: [
    {
      id: 'the-fields-run-on-you',
      type: 'count',
      token: 'act:farm_paddy',
      target: 20,
      flavor: `"The fields keep a man's hours now, and not mine — if mine ever held them," comes ${NAMES.lord}'s voice through the screen of the inner house, unanswered; the yard knows whose hours he means.`,
      objective: 'The fields keep his hours, and the water follows them.',
      drive: 'farm_paddy',
    },
    {
      id: 'the-woodlot-runs-on-you',
      type: 'count',
      token: 'act:woodcut_edge',
      target: 20,
      flavor: `"Even the woodlot answers to him," ${NAMES.drillmaster} says to ${NAMES.elder}, who does not disagree.`,
      objective: 'The woodlot is cut on his rotation, stand by stand.',
      drive: 'woodcut_edge',
    },
    {
      id: 'a-granary-against-winter',
      type: 'state',
      pred: { kind: 'banked', res: 'rice', min: 200 },
      flavor: `"There is rice against winter. There was a saying for that — I had it once," ${NAMES.lord} is heard saying to the dark of the inner house, and nobody who hears it goes in.`,
      objective: 'The granary is full to the rafters against the winter.',
      drive: 'deposit rice',
    },
    {
      id: 'the-nengu-reckoned',
      type: 'flag',
      flag: 'nengu-reckoned',
      flavor:
        'You stood in the room while the year was measured against the house — the reckoning read out, the gap named plainly and once, and nothing asked of you but to be there for it. A full year, lived through.',
      objective: 'The nengu bales stand roped at the gate, the year closed.',
      drive: 'sim reaches the Autumn season-exit, whose nengu ceremony sets `nengu-reckoned`.',
    },
  ],
};
