// GENERATED by `pnpm run gen:narrative` from src/core/content/narrative/requirements.md — DO NOT EDIT.
// Hand edits here are drift by definition: edit the markdown source and regenerate
// (the gen-narrative verify gate rebuilds this file and byte-compares it).
// Data only — the types + helpers stay hand-written in requirements.ts, which re-exports this.

import type { RequirementDef } from '../requirements-engine';
import type { RankId } from './ranks';
import { NAMES } from './names';

export const RUNG_REQUIREMENTS: Readonly<Record<RankId, readonly RequirementDef[]>> = {
  R0: [
    {
      id: 'rake-the-spill',
      type: 'count',
      token: 'act:rake_rice',
      target: 500,
      flavor: `The spilled stores are swept to rows; ${NAMES.elder} counts them without a word.`,
      drive: 'rake_rice',
    },
  ],

  R1: [
    {
      id: 'take-to-the-fields',
      type: 'count',
      token: 'act:farm_paddy',
      target: 600,
      flavor: 'The paddies answer your hand now; the green rows stand straighter for it.',
      drive: 'farm_paddy',
    },
    {
      id: 'a-porters-back',
      type: 'count',
      token: 'act:haul_stores',
      target: 400,
      flavor: 'The porters stop watching you lift. That is its own approval.',
      drive: 'haul_stores',
    },
  ],

  R2: [
    {
      id: 'learn-the-woodlot',
      type: 'count',
      token: 'act:woodcut_edge',
      target: 350,
      flavor: 'The woodlot edge knows your axe; the stack by the kura grows even.',
      drive: 'woodcut_edge',
    },
    {
      id: 'walk-the-hills',
      type: 'count',
      token: 'act:forage_satoyama',
      target: 350,
      flavor: 'You come back from the hills with full baskets and no bad stories.',
      drive: 'forage_satoyama',
    },
    {
      id: 'keep-the-stores-moving',
      type: 'count',
      token: 'act:haul_stores',
      target: 300,
      flavor: 'A hand that keeps hauling after the field work is a hand the house notes.',
      drive: 'haul_stores',
    },
    {
      id: 'face-the-wolf',
      type: 'flag',
      flag: 'first-fight-survived',
      flavor: 'The grain-store wolf is faced. The story runs the estate faster than you walk it.',
      drive: 'face_wolf',
    },
  ],

  R3: [
    {
      id: 'clear-the-kura-rats',
      type: 'count',
      token: 'kill:rice_rats',
      target: 3,
      flavor: 'The rats learn the kura has teeth again.',
      drive: 'fight rice_rats',
    },
    {
      id: 'drive-off-the-thieves',
      type: 'count',
      token: 'kill:monkey',
      target: 2,
      flavor: "The paddies' thieves grow careful where you stand a watch.",
      drive: 'fight monkey',
    },
    {
      id: 'keep-the-rows',
      type: 'count',
      token: 'act:farm_paddy',
      target: 400,
      flavor: `Watch or no watch, your rows never fall behind — ${NAMES.drillmaster} marks that.`,
      drive: 'farm_paddy',
    },
    {
      id: 'timber-for-the-palisade',
      type: 'count',
      token: 'act:woodcut_edge',
      target: 300,
      flavor: 'Timber for the palisade, cut on your own hours.',
      drive: 'woodcut_edge',
    },
  ],

  R4: [
    {
      id: 'the-stores-know-you',
      type: 'count',
      token: 'act:haul_stores',
      target: 450,
      flavor: 'The stores move through your hands like they were born to it.',
      drive: 'haul_stores',
    },
    {
      id: 'mend-your-own-blade',
      type: 'count',
      token: 'act:repair_weapon',
      target: 1,
      flavor: `A blade mended by its own bearer — ${NAMES.elder} hears of it from ${NAMES.smith}.`,
      drive: 'repair_weapon',
    },
    {
      id: 'thin-the-near-wolves',
      type: 'count',
      token: 'kill:wolf',
      target: 2,
      flavor: 'Two wolves fewer on the near hills; the herders sleep easier.',
      drive: 'fight wolf',
    },
    {
      id: 'a-hundred-mon-held',
      type: 'state',
      pred: { kind: 'resource', res: 'coin', min: 100 },
      flavor: 'A hundred mon of your own keeping. The house trusts a hand that can hold money.',
      drive: 'sell rice',
    },
  ],

  R5: [
    {
      id: 'past-the-danger-line',
      type: 'count',
      token: 'act:forage_deepwoods',
      target: 200,
      flavor: 'The deep satoyama yields to you now, a hill past where the others turn back.',
      drive: 'forage_deepwoods',
    },
    {
      id: 'the-fence-breaker',
      type: 'count',
      token: 'kill:boar',
      target: 1,
      flavor: 'The boar that tore the fences is down. The field hands say your name differently.',
      drive: 'fight boar',
    },
    {
      id: 'the-paddies-still-first',
      type: 'count',
      token: 'act:farm_paddy',
      target: 300,
      flavor: 'The paddies still come first. They always came first.',
      drive: 'farm_paddy',
    },
    {
      id: 'a-made-corner',
      type: 'state',
      pred: { kind: 'belonging', id: 'bedding' },
      flavor: 'A made bed in your own corner — you live here now, and the house knows it.',
      drive: 'buy bedding',
    },
  ],

  R6: [
    {
      id: 'the-ledgers-agree',
      type: 'count',
      token: 'act:haul_stores',
      target: 400,
      flavor: 'The ledgers and your shoulders have stopped arguing with each other.',
      drive: 'haul_stores',
    },
    {
      id: 'three-hundred-mon-steady',
      type: 'state',
      pred: { kind: 'resource', res: 'coin', min: 300 },
      flavor: "Three hundred mon held steady through a season's spending.",
      drive: 'sell rice',
    },
    {
      id: 'coin-into-the-works',
      type: 'state',
      pred: { kind: 'native', key: 'estate-u1' },
      flavor: 'The kura-works stand a stage better for coin you put back into the house.',
      drive: 'buy estate_upgrade',
    },
    {
      id: 'clear-the-woodlot-road',
      type: 'count',
      token: 'kill:bandit',
      target: 1,
      flavor: 'The man who watched the woodlot road watches nothing now.',
      drive: 'fight bandit',
    },
  ],

  R7: [
    {
      id: 'the-fields-run-on-you',
      type: 'count',
      token: 'act:farm_paddy',
      target: 400,
      flavor: "The house's fields run on your rhythm now, not the other way around.",
      drive: 'farm_paddy',
    },
    {
      id: 'the-woodlot-runs-on-you',
      type: 'count',
      token: 'act:woodcut_edge',
      target: 400,
      flavor: "The woodlot's stack stands winter-deep, and it was your axe that made it so.",
      drive: 'woodcut_edge',
    },
    {
      id: 'a-granary-against-winter',
      type: 'state',
      pred: { kind: 'banked', res: 'rice', min: 200 },
      flavor: 'The granary holds deep against winter, and the ledger names you for it.',
      drive: 'deposit rice',
    },
    {
      id: 'no-argument-unanswered',
      type: 'count',
      token: 'kill:boar',
      target: 2,
      flavor: "The deep woods hold no argument you haven't answered.",
      drive: 'fight boar',
    },
  ],
};
