// GENERATED by `pnpm run gen:narrative` from src/core/content/narrative/scenes.md — DO NOT EDIT.
// Hand edits here are drift by definition: edit the markdown source and regenerate
// (the gen-narrative verify gate rebuilds this file and byte-compares it).
// Data only — the types + helpers stay hand-written in scenes.ts, which re-exports this.

import type { SceneDef } from './scenes';
import { NPC_NAME } from './voices';

export const SCENES: readonly SceneDef[] = [
  {
    id: 'nengu-autumn-frame',
    scene: {
      id: 'nengu-autumn-frame',
      voice: 'narrator',
      motivates: [],
      greeting: [
        {
          voice: 'narrator',
          text: "First light. The broom stands against the gatepost where you left it. The hand who kept the yard's round quit for the lowlands; nobody has said whose it is now.",
        },
        { voice: 'narrator', text: 'You take the broom. Nobody takes it back.' },
      ],
      topics: [],
      decision: { prompt: '', options: [] },
    },
    trigger: { kind: 'season-exit', season: 'autumn' },
    once: true,
  },

  {
    id: 'sb-dog',
    scene: {
      id: 'sb-dog',
      voice: 'arms',
      speaker: 'kihei',
      motivates: [],
      greeting: [
        {
          voice: 'narrator',
          text: 'The last of the pack went over the wall two days ago. This one stayed. An old dog, grey to the jaw, one ear ragged from winters, lying in the dead leaves under the far fruit trees like the orchard is a post it was never relieved from.',
        },
        {
          voice: 'narrator',
          text: 'It does not run and it does not beg. When you work, it watches. When you eat, it watches the food, then you — and then it looks away first.',
        },
        {
          voice: 'narrator',
          text: 'Kihei crosses the cleared ground on his round and stops beside you, reading the dog the way he reads a blade for rust.',
        },
        {
          voice: 'arms',
          speaker: NPC_NAME.kihei,
          text: '"The old one. Too slow for the pack, too proud for the village middens. Drive it, feed it, or bring it to me. Don\'t leave it half-decided."',
        },
      ],
      topics: [],
      decision: {
        prompt: 'The dog watches you decide.',
        options: [
          {
            id: 'sb-dog-drive',
            label: '"The orchard\'s cleared. All of it."',
            say: '"The orchard\'s cleared. All of it."',
            react: '"Cleared is cleared. Stop the gap in the wall behind it."',
            memory: [{ npc: 'kihei', warmthDelta: 1, regard: 'thorough' }],
            flags: ['sb-dog-driven'],
          },
          {
            id: 'sb-dog-feed',
            label: '"It stays. I\'ll feed it from my share."',
            say: '"It stays. I\'ll feed it from my share."',
            react:
              '"A dog. Old, one ear. Rice: a handful, mornings, from the sweepings — entered against rats. If it earns, it stays entered."',
            reactNpc: 'genemon',
            memory: [{ npc: 'genemon', warmthDelta: 1, regard: 'accountable' }],
            flags: ['sb-dog-fed'],
          },
          {
            id: 'sb-dog-kihei',
            label: '"Take it to Kihei."',
            say: '"Take it to Kihei."',
            react: '"Give me your belt-cord. Go rake the leaves. This isn\'t a lesson."',
            memory: [{ npc: 'kihei', warmthDelta: 1, regard: 'clear-eyed' }],
            flags: ['sb-dog-ended'],
          },
        ],
      },
    },
    trigger: { kind: 'flag', flag: 'orchard-reclaimed' },
    once: true,
  },
];
