// Persona-bot balance sim CLI (F4 §5) — drives the REAL engine with the persona roster over the
// gating seed matrix and reports pacing shape. Modes:
//   (no flag)    per-rung pacing table + per-seed summaries (console)
//   --report     regenerate docs/content/t0-pacing.md (gen-docs pattern: committed, diffable)
//   --selftest   the Ph1 DoD asserts (walkPacing R0–R2 equality · determinism · all seeds ascend)
//   --fuzz N     N derived seeds, STRUCTURAL checks only (soft-locks are bugs at any seed);
//                fuzz never gates envelopes. Output → console only.
// Envelope gating (`--check`) + the report fingerprint (`--check-fresh`) land in Ph2.
export {};

import { writeFileSync } from 'node:fs';
import { balance } from '../core';
import { PERSONAS, greedy, skippedIntents, type Persona } from '../sim/personas';
import { runPersona } from '../sim/run';
import type { RunMetrics, RungMetric } from '../sim/metrics';
import { wallMinutes } from '../sim/metrics';
import { SIM_SEEDS, CANONICAL_SEED, fuzzSeeds } from '../sim/seeds';
import { walkPacing } from './pacing-report';

const OUT = 'docs/content/t0-pacing.md';

// ── run the matrix ────────────────────────────────────────────────────────────────────────────

interface PersonaRuns {
  persona: Persona;
  runs: RunMetrics[]; // one per SIM_SEEDS entry, in order
}

function runMatrix(): PersonaRuns[] {
  return PERSONAS.map((persona) => ({
    persona,
    runs: SIM_SEEDS.map((seed) => runPersona(persona, seed).metrics),
  }));
}

function median(xs: number[]): number {
  const s = [...xs].sort((a, b) => a - b);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 ? s[mid]! : (s[mid - 1]! + s[mid]!) / 2;
}

function rungRow(runs: RunMetrics[], rung: string): RungMetric[] {
  return runs
    .map((r) => r.rungs.find((x) => x.rung === rung))
    .filter((x): x is RungMetric => x !== undefined);
}

const min1 = (n: number): string => n.toFixed(1);
const RUNG_ORDER = ['R0', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7'] as const;

// ── report / table rendering ──────────────────────────────────────────────────────────────────

function personaSection(pr: PersonaRuns): string[] {
  const L: string[] = [];
  const canonical = pr.runs[SIM_SEEDS.indexOf(CANONICAL_SEED)]!;

  L.push(`## ${pr.persona.id} — time-to-rung`);
  L.push('');
  L.push(
    `Wall-minutes per rung: median [min–max] across seeds ${SIM_SEEDS.join(', ')}; ` +
      `acts/rests/moves from the canonical seed ${CANONICAL_SEED}.`,
  );
  L.push('');
  L.push(
    '| rung | threshold | acts | rests | moves | intents | wall-min | across seeds | cum med |',
  );
  L.push('|---|---|---|---|---|---|---|---|---|');
  let cum = 0;
  for (const rung of RUNG_ORDER) {
    const rows = rungRow(pr.runs, rung);
    if (rows.length === 0) continue;
    const c = canonical.rungs.find((x) => x.rung === rung);
    const mins = rows.map((r) => r.wallMin);
    const med = median(mins);
    cum += med;
    L.push(
      `| ${rung} | ${rows[0]!.threshold} | ${c?.acts ?? '—'} | ${c?.rests ?? '—'} | ` +
        `${c?.moves ?? '—'} | ${c?.intents ?? '—'} | ${min1(med)} | ` +
        `[${min1(Math.min(...mins))}–${min1(Math.max(...mins))}] | ${min1(cum)} |`,
    );
  }
  L.push('');

  L.push(`## ${pr.persona.id} — arc + economy (per seed)`);
  L.push('');
  L.push(
    '| seed | ascended | intents | wall-min | Phase-2 min | first-coin min | end coin | end rice | estate |',
  );
  L.push('|---|---|---|---|---|---|---|---|---|');
  for (const r of pr.runs) {
    const p2 = r.economy.phase2Intents;
    const fc = r.economy.firstCoinIntent;
    L.push(
      `| ${r.seed} | ${r.ascended ? '✅' : '❌ ' + (r.softLock?.reason ?? 'no')} | ` +
        `${r.totalIntents} | ${min1(r.totalWallMin)} | ${p2 === null ? '—' : min1(wallMinutes(p2))} | ` +
        `${fc === null ? '—' : min1(wallMinutes(fc))} | ${r.economy.endCoin} | ${r.economy.endRice} | ` +
        `${r.economy.endEstate} |`,
    );
  }
  L.push('');

  L.push(`## ${pr.persona.id} — combat · starvation · durability (per seed)`);
  L.push('');
  L.push(
    '| seed | fights | W/L/R | coin bled | rice bled | satiety-0 | below-knee | battered | max no-progress |',
  );
  L.push('|---|---|---|---|---|---|---|---|---|');
  for (const r of pr.runs) {
    L.push(
      `| ${r.seed} | ${r.combat.fights} | ${r.combat.wins}/${r.combat.losses}/${r.combat.retreats} | ` +
        `${r.combat.lossCoinBled} | ${r.combat.lossRiceBled} | ${r.starvation.zeroSatietyIntents} | ` +
        `${r.starvation.belowKneeIntents} | ${r.durability.batteredIntents} | ` +
        `${r.maxIntentsWithoutProgress} |`,
    );
  }
  L.push('');
  return L;
}

function generateReport(matrix: PersonaRuns[]): string {
  const L: string[] = [];
  L.push('# T0 pacing report (GENERATED)');
  L.push('');
  L.push('> GENERATED by `npm run balance:report` (`src/scripts/balance-sim.ts`) — persona bots');
  L.push('> driving the REAL engine over the gating seed matrix. Do not edit by hand; change');
  L.push('> balance/content and regenerate. `git diff` on this file IS the before/after of a');
  L.push('> balance change (F4 §5b).');
  L.push('');
  L.push(`- Seeds: ${SIM_SEEDS.join(', ')} (canonical: ${CANONICAL_SEED})`);
  L.push(`- Personas: ${PERSONAS.map((p) => p.id).join(', ')}`);
  L.push(
    `- Wall model: one intent per ${balance.AUTO_REPEAT_MS} ms (the active-loop cadence) — ` +
      `wall-min = intents × ${balance.AUTO_REPEAT_MS} / 60000. Every dispatch counts (moves and`,
  );
  L.push('  story beats included), so the model reflects what the auto-loop actually issues.');
  L.push(
    `- T0 climb band (D-056): [${balance.T0_PACING_BAND_MIN}, ${balance.T0_PACING_BAND_MAX}] ` +
      'wall-min per climb rung. Envelope VERDICTS land with `verify:balance` (F4 Ph2);',
  );
  L.push('  this report is the measurement.');
  L.push('');
  for (const pr of matrix) L.push(...personaSection(pr));

  L.push('## Skipped intents (per persona — loud, never a silent gap)');
  L.push('');
  for (const p of PERSONAS) {
    L.push(`- **${p.id}** never issues: ${skippedIntents(p).join(', ')}`);
  }
  L.push('');
  return L.join('\n');
}

// ── self-test (the Ph1 DoD, machine-checkable) ────────────────────────────────────────────────

function selftest(): number {
  let failures = 0;
  const fail = (msg: string): void => {
    failures++;
    console.error(`SELFTEST FAIL: ${msg}`);
  };
  const ok = (msg: string): void => console.log(`selftest ok: ${msg}`);

  // (1) greedy reproduces the KNOWN current pacing: R0–R2 buckets equal walkPacing() exactly
  //     on the canonical seed (same shared policy ⇒ equality, not tolerance).
  const walk = walkPacing(CANONICAL_SEED);
  const sim = runPersona(greedy, CANONICAL_SEED).metrics;
  for (const rung of ['R0', 'R1', 'R2'] as const) {
    const w = walk.find((r) => r.rung === rung)!;
    const s = sim.rungs.find((r) => r.rung === rung);
    if (!s) {
      fail(`${rung}: missing from sim run`);
      continue;
    }
    const walkCompat = s.acts + s.rests + s.meta;
    if (s.acts !== w.acts || s.rests !== w.rests || s.meta !== w.meta || walkCompat !== w.intents) {
      fail(
        `${rung}: sim acts/rests/meta ${s.acts}/${s.rests}/${s.meta} (=${walkCompat}) ≠ ` +
          `walkPacing ${w.acts}/${w.rests}/${w.meta} (=${w.intents})`,
      );
    } else ok(`${rung} equals walkPacing (${w.acts} acts, ${w.rests} rests, ${w.meta} meta)`);
  }

  // (2) determinism: the same seed twice ⇒ byte-identical RunMetrics.
  const again = runPersona(greedy, CANONICAL_SEED).metrics;
  if (JSON.stringify(sim) !== JSON.stringify(again))
    fail('same seed produced different RunMetrics');
  else ok(`deterministic on seed ${CANONICAL_SEED} (${sim.totalIntents} intents)`);

  // (3) the full arc closes on every gating seed (tier 0 → 1, no soft-lock) — cross-checks
  //     t0-arc.test.ts's result through real `fight` intents instead of applyGrindFight.
  for (const seed of SIM_SEEDS) {
    const m = seed === CANONICAL_SEED ? sim : runPersona(greedy, seed).metrics;
    if (!m.ascended || m.softLock) {
      fail(`seed ${seed}: did not ascend (softLock=${JSON.stringify(m.softLock)})`);
    } else ok(`seed ${seed} ascends (${m.totalIntents} intents, ${min1(m.totalWallMin)} min)`);
  }
  return failures;
}

// ── CLI ───────────────────────────────────────────────────────────────────────────────────────

const RUN_AS_CLI = process.argv[1]?.includes('balance-sim') ?? false;
if (RUN_AS_CLI) {
  const args = process.argv.slice(2);
  if (args.includes('--selftest')) {
    const failures = selftest();
    process.exit(failures ? 1 : 0);
  } else if (args.includes('--fuzz')) {
    const n = Number(args[args.indexOf('--fuzz') + 1] ?? 10);
    const seeds = fuzzSeeds(CANONICAL_SEED, n);
    let broken = 0;
    for (const seed of seeds) {
      const m = runPersona(greedy, seed).metrics;
      const flag = m.ascended && !m.softLock ? 'ok' : 'STRUCTURAL RED';
      if (flag !== 'ok') broken++;
      console.log(
        `fuzz seed ${String(seed).padStart(10)}: ${flag} — ${m.totalIntents} intents, ` +
          `${min1(m.totalWallMin)} min, ${m.combat.wins}/${m.combat.losses}/${m.combat.retreats} W/L/R`,
      );
    }
    console.log(`FUZZ: ${seeds.length} seeds, ${broken} structural break(s)`);
    process.exit(broken ? 1 : 0);
  } else if (args.includes('--report')) {
    const started = performance.now();
    const matrix = runMatrix();
    writeFileSync(OUT, generateReport(matrix));
    console.log(
      `wrote ${OUT} (${PERSONAS.length} persona(s) × ${SIM_SEEDS.length} seeds in ` +
        `${((performance.now() - started) / 1000).toFixed(1)}s)`,
    );
  } else {
    // console table — the quick look (the report is the committed artifact).
    const matrix = runMatrix();
    for (const pr of matrix) {
      console.log(generateReport([pr]));
    }
  }
}
