// gen-narrative (FB-5) — compile the narrative authoring markdown into generated TS registries.
//
// Mirrors gen-docs.ts, INVERTED: the `.md` under src/core/content/narrative/ is the source
// of truth and the `.gen.ts` is the artifact. Bare = write; `--check` regenerates into a
// buffer and byte-compares — drift (including a hand edit to a generated file) goes RED
// with an error naming the markdown to edit instead.
//
// All narrative files are parsed FIRST and validated AS A SET (cross-file reuse references
// and dialogue routing need the whole picture), then each compiles independently. The
// emitted source is piped through oxfmt (the repo formatter, via --stdin-filepath) so the
// on-disk bytes are stable and pass the `oxfmt --check` gate untouched.
export {};

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { parseNarrative, NarrativeError, type NarrativeDoc } from './narrative/parse';
import {
  emitColdOpen,
  emitDialogue,
  emitFlavor,
  emitIntro,
  emitRequirements,
  emitRungBeats,
} from './narrative/emit';
import { emitStoryDoc } from './narrative/story-doc';
import { validateNarrative } from './narrative/validate';
import { emitStoryTakes, parseBundleMeta, type ParsedTakeBundle } from './narrative/takes';

const repoRoot = fileURLToPath(new URL('../../', import.meta.url));

interface Target {
  readonly md: string;
  readonly out: string;
  readonly emit: (doc: NarrativeDoc) => string;
}

const TARGETS: readonly Target[] = [
  {
    md: 'src/core/content/narrative/rung-beats.md',
    out: 'src/core/content/rungBeats.gen.ts',
    emit: emitRungBeats,
  },
  {
    md: 'src/core/content/narrative/intro.md',
    out: 'src/core/content/intro.gen.ts',
    emit: emitIntro,
  },
  {
    md: 'src/core/content/narrative/dialogue.md',
    out: 'src/core/content/dialogue.gen.ts',
    emit: emitDialogue,
  },
  {
    md: 'src/core/content/narrative/cold-open.md',
    out: 'src/core/content/coldOpen.gen.ts',
    emit: emitColdOpen,
  },
  {
    md: 'src/core/content/narrative/flavor.md',
    out: 'src/core/content/flavor.gen.ts',
    emit: emitFlavor,
  },
  {
    md: 'src/core/content/narrative/requirements.md',
    out: 'src/core/content/requirements.gen.ts',
    emit: emitRequirements,
  },
];

/** Format TS source with the repo formatter so generated bytes match `oxfmt --check`. */
function format(source: string, outPath: string): string {
  const oxfmt = join(repoRoot, 'node_modules/.bin/oxfmt');
  const r = spawnSync(oxfmt, [`--stdin-filepath=${join(repoRoot, outPath)}`], {
    cwd: repoRoot,
    input: source,
    encoding: 'utf-8',
  });
  if (r.status !== 0) {
    throw new Error(`oxfmt failed on generated ${outPath}:\n${r.stderr || r.stdout}`);
  }
  return r.stdout;
}

const check = process.argv.includes('--check');
let drift = 0;

try {
  // Parse everything first — validation is a whole-set concern.
  const present = TARGETS.filter((t) => existsSync(join(repoRoot, t.md)));
  const docs = new Map<string, NarrativeDoc>(
    present.map((t) => [t.md, parseNarrative(readFileSync(join(repoRoot, t.md), 'utf-8'), t.md)]),
  );
  const verdict = validateNarrative([...docs.values()]);
  for (const w of verdict.warnings) console.warn(`  ~ gen-narrative WARN: ${w}`);
  if (verdict.errors.length) {
    for (const e of verdict.errors) console.error(`  X gen-narrative: ${e}`);
    process.exit(1);
  }

  for (const t of present) {
    const generated = format(t.emit(docs.get(t.md)!), t.out);
    const outAbs = join(repoRoot, t.out);
    if (check) {
      const onDisk = existsSync(outAbs) ? readFileSync(outAbs, 'utf-8') : '';
      if (onDisk !== generated) {
        console.error(
          `  X gen-narrative: ${t.out} is out of date (or hand-edited).\n` +
            `    The source of truth is ${t.md} — edit THAT, then run \`pnpm run gen:narrative\`.`,
        );
        drift++;
      }
    } else {
      writeFileSync(outAbs, generated);
      console.log(`  gen-narrative: wrote ${t.out} (from ${t.md})`);
    }
  }
  // The one-page reading script (Ph4) — drift-checked like the modules; markdown,
  // so no formatter pass (docs/*.md are oxfmt-ignored).
  const STORY_OUT = 'docs/content/t0-story.md';
  const story = emitStoryDoc([...docs.values()]);
  const storyAbs = join(repoRoot, STORY_OUT);
  if (check) {
    const onDisk = existsSync(storyAbs) ? readFileSync(storyAbs, 'utf-8') : '';
    if (onDisk !== story) {
      console.error(
        `  X gen-narrative: ${STORY_OUT} is out of date (or hand-edited/deleted).\n` +
          `    It regenerates from src/core/content/narrative/*.md — run \`pnpm run gen:narrative\`.`,
      );
      drift++;
    }
  } else {
    writeFileSync(storyAbs, story);
    console.log(`  gen-narrative: wrote ${STORY_OUT}`);
  }

  // Story take-sets (ADR-139) — open narrative-diverge bundles under
  // narrative/takes/<bundle>/ compile into the DEV-only registry. Always
  // emitted (a stable empty array when no bundle is open) so the byte-compare
  // has a fixed target.
  const TAKES_DIR = 'src/core/content/narrative/takes';
  const TAKES_OUT = 'src/ui/storyTakes.gen.ts';
  const takesAbs = join(repoRoot, TAKES_DIR);
  const bundleIds = existsSync(takesAbs)
    ? readdirSync(takesAbs, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name)
        .sort()
    : [];
  const bundles: ParsedTakeBundle[] = bundleIds.map((b) => {
    const metaPath = `${TAKES_DIR}/${b}/bundle.md`;
    const meta = parseBundleMeta(readFileSync(join(repoRoot, metaPath), 'utf-8'), metaPath);
    const docs = meta.takes.map((t) => {
      const p = `${TAKES_DIR}/${b}/${t.file}`;
      return parseNarrative(readFileSync(join(repoRoot, p), 'utf-8'), p);
    });
    return { meta, docs };
  });
  const takesGenerated = format(emitStoryTakes(bundles), TAKES_OUT);
  const takesOutAbs = join(repoRoot, TAKES_OUT);
  if (check) {
    const onDisk = existsSync(takesOutAbs) ? readFileSync(takesOutAbs, 'utf-8') : '';
    if (onDisk !== takesGenerated) {
      console.error(
        `  X gen-narrative: ${TAKES_OUT} is out of date (or hand-edited).\n` +
          `    The source of truth is ${TAKES_DIR}/ — edit THAT, then run \`pnpm run gen:narrative\`.`,
      );
      drift++;
    }
  } else {
    writeFileSync(takesOutAbs, takesGenerated);
    console.log(`  gen-narrative: wrote ${TAKES_OUT} (${bundles.length} open bundle(s))`);
  }

  if (check) {
    if (drift) process.exit(1);
    console.log(
      `  gen-narrative: ${present.length} module(s) + ${STORY_OUT} + ${TAKES_OUT} in sync`,
    );
  }
} catch (e) {
  if (e instanceof NarrativeError) {
    console.error(`  X gen-narrative: ${e.message}`);
    process.exit(1);
  }
  throw e;
}
