// Generated-docs gate (PRD §6.6): regenerates content docs from the SAME typed data
// the game uses (generate-don't-duplicate). `--check` regenerates into a buffer and
// fails the build on drift; bare `gen:docs` writes. Grows as registries arrive.
export {};

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { SURFACES, NAMES, SKILLS, ACTIVITIES, RANKS, MOBS, WEAPONS, ESTATE_STAGES } from '../core';

const OUT = 'docs/content/t0-content.md';

function generate(): string {
  const L: string[] = [];
  L.push('# T0 content (GENERATED)');
  L.push('');
  L.push('> GENERATED by `npm run gen:docs` from the typed content registries');
  L.push('> (`src/core/content/*`). Do not edit by hand — edit the registry and regenerate.');
  L.push('');

  L.push('## Rung ladder (T0 — Estate)');
  L.push('');
  L.push('| rung | title | kanji | meter | eligible | granter |');
  L.push('|---|---|---|---|---|---|');
  for (const r of RANKS) {
    L.push(
      `| ${r.id} | ${r.title} | ${r.kanji} | ${r.meterThreshold} | ${r.eligible.join(', ')} | ${r.granter ?? '—'} |`,
    );
  }
  L.push('');

  L.push('## Skills (v1 labour set)');
  L.push('');
  L.push('| id | label | kanji |');
  L.push('|---|---|---|');
  for (const s of SKILLS) L.push(`| ${s.id} | ${s.label} | ${s.kanji} |`);
  L.push('');

  L.push('## Labour activities');
  L.push('');
  L.push('| id | skill | area | yields | satiety | xp |');
  L.push('|---|---|---|---|---|---|');
  for (const a of ACTIVITIES) {
    const yields = Object.entries(a.yields)
      .map(([r, n]) => `${n} ${r}`)
      .join(', ');
    L.push(`| ${a.id} | ${a.skill} | ${a.area} | ${yields} | ${a.satietyCost} | ${a.xp} |`);
  }
  L.push('');

  L.push('## Weapons (T0 roster)');
  L.push('');
  L.push('| id | label | atk | speed | durability | archetype |');
  L.push('|---|---|---|---|---|---|');
  for (const w of WEAPONS) {
    L.push(
      `| ${w.id} | ${w.label} | ${w.baseAttack} | ${w.baseSpeed} | ${w.durabilityMax} | ${w.archetype} |`,
    );
  }
  L.push('');

  L.push('## Bestiary (grounded — no belief-creatures)');
  L.push('');
  L.push('| id | label | level | koku | scripted |');
  L.push('|---|---|---|---|---|');
  for (const m of MOBS) {
    L.push(`| ${m.id} | ${m.label} | ${m.level} | ${m.kokuReward} | ${m.scripted ? 'yes' : ''} |`);
  }
  L.push('');

  L.push('## Estate improvements (koku sink)');
  L.push('');
  L.push('| stage | label | koku | +satietyMax |');
  L.push('|---|---|---|---|');
  for (const e of ESTATE_STAGES) {
    L.push(`| E${e.stage} | ${e.label} | ${e.kokuCost} | +${e.satietyMaxBonus} |`);
  }
  L.push('');

  L.push('## Surfaces (reveal registry)');
  L.push('');
  L.push('| id | kind |');
  L.push('|---|---|');
  for (const s of SURFACES) L.push(`| \`${s.id}\` | ${s.kind} |`);
  L.push('');

  L.push('## Cast — canonical display names (force-fictionalised)');
  L.push('');
  L.push('| key | name |');
  L.push('|---|---|');
  for (const [key, value] of Object.entries(NAMES)) L.push(`| ${key} | ${value} |`);
  L.push('');
  return L.join('\n');
}

const check = process.argv.includes('--check');
const content = generate();

if (check) {
  const existing = existsSync(OUT) ? readFileSync(OUT, 'utf-8') : '';
  if (existing !== content) {
    console.error(`gen:docs --check FAILED: ${OUT} is stale. Run \`npm run gen:docs\`.`);
    process.exit(1);
  }
  console.log('gen:docs --check: generated docs are up to date.');
} else {
  mkdirSync('docs/content', { recursive: true });
  writeFileSync(OUT, content, 'utf-8');
  console.log(`gen:docs: wrote ${OUT}.`);
}
process.exit(0);
