// gen-narrative (F5) — compile the narrative authoring markdown into generated TS registries.
//
// Mirrors gen-docs.ts, INVERTED: the `.md` under src/core/content/narrative/ is the source
// of truth and the `.gen.ts` is the artifact. Bare = write; `--check` regenerates into a
// buffer and byte-compares — drift (including a hand edit to a generated file) goes RED
// with an error naming the markdown to edit instead.
//
// The emitted source is piped through oxfmt (the repo formatter, via --stdin-filepath) so
// the on-disk bytes are stable and pass the `oxfmt --check` gate untouched.
export {};

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { parseNarrative, NarrativeError } from './narrative/parse';
import { emitRungBeats } from './narrative/emit';

const repoRoot = fileURLToPath(new URL('../../', import.meta.url));

interface Target {
  readonly md: string;
  readonly out: string;
  readonly emit: (doc: ReturnType<typeof parseNarrative>) => string;
}

const TARGETS: readonly Target[] = [
  {
    md: 'src/core/content/narrative/rung-beats.md',
    out: 'src/core/content/rungBeats.gen.ts',
    emit: emitRungBeats,
  },
];

/** Format TS source with the repo formatter so generated bytes match `oxfmt --check`. */
function format(source: string, outPath: string): string {
  const oxfmt = join(repoRoot, 'node_modules/.bin/oxfmt');
  const r = spawnSync(oxfmt, [`--stdin-filepath=${join(repoRoot, outPath)}`], {
    cwd: repoRoot,
    input: source,
    encoding: 'utf-8',
  });
  if (r.status !== 0) {
    throw new Error(`oxfmt failed on generated ${outPath}:\n${r.stderr || r.stdout}`);
  }
  return r.stdout;
}

const check = process.argv.includes('--check');
let drift = 0;

for (const t of TARGETS) {
  let generated: string;
  try {
    const doc = parseNarrative(readFileSync(join(repoRoot, t.md), 'utf-8'), t.md);
    generated = format(t.emit(doc), t.out);
  } catch (e) {
    if (e instanceof NarrativeError) {
      console.error(`  X gen-narrative: ${e.message}`);
      process.exit(1);
    }
    throw e;
  }
  const outAbs = join(repoRoot, t.out);
  if (check) {
    const onDisk = existsSync(outAbs) ? readFileSync(outAbs, 'utf-8') : '';
    if (onDisk !== generated) {
      console.error(
        `  X gen-narrative: ${t.out} is out of date (or hand-edited).\n` +
          `    The source of truth is ${t.md} — edit THAT, then run \`npm run gen:narrative\`.`,
      );
      drift++;
    }
  } else {
    writeFileSync(outAbs, generated);
    console.log(`  gen-narrative: wrote ${t.out} (from ${t.md})`);
  }
}

if (check) {
  if (drift) process.exit(1);
  console.log(`  gen-narrative: ${TARGETS.length} generated module(s) in sync`);
}
