// gen-narrative (F5) — compile the narrative authoring markdown into generated TS registries.
//
// Mirrors gen-docs.ts, INVERTED: the `.md` under src/core/content/narrative/ is the source
// of truth and the `.gen.ts` is the artifact. Bare = write; `--check` regenerates into a
// buffer and byte-compares — drift (including a hand edit to a generated file) goes RED
// with an error naming the markdown to edit instead.
//
// All narrative files are parsed FIRST and validated AS A SET (cross-file reuse references
// and dialogue routing need the whole picture), then each compiles independently. The
// emitted source is piped through oxfmt (the repo formatter, via --stdin-filepath) so the
// on-disk bytes are stable and pass the `oxfmt --check` gate untouched.
export {};

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { parseNarrative, NarrativeError, type NarrativeDoc } from './narrative/parse';
import { emitColdOpen, emitDialogue, emitIntro, emitRungBeats } from './narrative/emit';
import { validateNarrative } from './narrative/validate';

const repoRoot = fileURLToPath(new URL('../../', import.meta.url));

interface Target {
  readonly md: string;
  readonly out: string;
  readonly emit: (doc: NarrativeDoc) => string;
}

const TARGETS: readonly Target[] = [
  {
    md: 'src/core/content/narrative/rung-beats.md',
    out: 'src/core/content/rungBeats.gen.ts',
    emit: emitRungBeats,
  },
  {
    md: 'src/core/content/narrative/intro.md',
    out: 'src/core/content/intro.gen.ts',
    emit: emitIntro,
  },
  {
    md: 'src/core/content/narrative/dialogue.md',
    out: 'src/core/content/dialogue.gen.ts',
    emit: emitDialogue,
  },
  {
    md: 'src/core/content/narrative/cold-open.md',
    out: 'src/core/content/coldOpen.gen.ts',
    emit: emitColdOpen,
  },
];

/** Format TS source with the repo formatter so generated bytes match `oxfmt --check`. */
function format(source: string, outPath: string): string {
  const oxfmt = join(repoRoot, 'node_modules/.bin/oxfmt');
  const r = spawnSync(oxfmt, [`--stdin-filepath=${join(repoRoot, outPath)}`], {
    cwd: repoRoot,
    input: source,
    encoding: 'utf-8',
  });
  if (r.status !== 0) {
    throw new Error(`oxfmt failed on generated ${outPath}:\n${r.stderr || r.stdout}`);
  }
  return r.stdout;
}

const check = process.argv.includes('--check');
let drift = 0;

try {
  // Parse everything first — validation is a whole-set concern.
  const present = TARGETS.filter((t) => existsSync(join(repoRoot, t.md)));
  const docs = new Map<string, NarrativeDoc>(
    present.map((t) => [t.md, parseNarrative(readFileSync(join(repoRoot, t.md), 'utf-8'), t.md)]),
  );
  const verdict = validateNarrative([...docs.values()]);
  for (const w of verdict.warnings) console.warn(`  ~ gen-narrative WARN: ${w}`);
  if (verdict.errors.length) {
    for (const e of verdict.errors) console.error(`  X gen-narrative: ${e}`);
    process.exit(1);
  }

  for (const t of present) {
    const generated = format(t.emit(docs.get(t.md)!), t.out);
    const outAbs = join(repoRoot, t.out);
    if (check) {
      const onDisk = existsSync(outAbs) ? readFileSync(outAbs, 'utf-8') : '';
      if (onDisk !== generated) {
        console.error(
          `  X gen-narrative: ${t.out} is out of date (or hand-edited).\n` +
            `    The source of truth is ${t.md} — edit THAT, then run \`npm run gen:narrative\`.`,
        );
        drift++;
      }
    } else {
      writeFileSync(outAbs, generated);
      console.log(`  gen-narrative: wrote ${t.out} (from ${t.md})`);
    }
  }
  if (check) {
    if (drift) process.exit(1);
    console.log(`  gen-narrative: ${present.length} generated module(s) in sync`);
  }
} catch (e) {
  if (e instanceof NarrativeError) {
    console.error(`  X gen-narrative: ${e.message}`);
    process.exit(1);
  }
  throw e;
}
