// Generated-docs gate (PRD §6.6): regenerates content docs from the SAME typed data
// the game uses (generate-don't-duplicate). `--check` regenerates into a buffer and
// fails the build on drift; bare `gen:docs` writes. Grows as registries arrive.
export {};

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import {
  SURFACES,
  NAMES,
  SKILLS,
  ACTIVITIES,
  RANKS,
  MOBS,
  WEAPONS,
  ESTATE_STAGES,
  MAP_NODES,
  MAP_NODE_CEILING,
  MARKET_ITEMS,
  STANCE_MODS,
  STANCE_ORDER,
  RECIPES,
  MATERIALS,
  MATERIAL_DROPS,
  SEASONS,
  balance,
} from '../core';

const OUT = 'docs/content/t0-content.md';

function generate(): string {
  const L: string[] = [];
  L.push('# T0 content (GENERATED)');
  L.push('');
  L.push('> GENERATED by `npm run gen:docs` from the typed content registries');
  L.push('> (`src/core/content/*`). Do not edit by hand — edit the registry and regenerate.');
  L.push('');

  L.push('## Rung ladder (T0 — Estate)');
  L.push('');
  L.push('| rung | title | kanji | meter | eligible | granter |');
  L.push('|---|---|---|---|---|---|');
  for (const r of RANKS) {
    L.push(
      `| ${r.id} | ${r.title} | ${r.kanji} | ${r.meterThreshold} | ${r.eligible.join(', ')} | ${r.granter ?? '—'} |`,
    );
  }
  L.push('');

  L.push('## Skills (v1 labour set)');
  L.push('');
  L.push('| id | label | kanji |');
  L.push('|---|---|---|');
  for (const s of SKILLS) L.push(`| ${s.id} | ${s.label} | ${s.kanji} |`);
  L.push('');

  L.push('## Labour activities');
  L.push('');
  L.push('| id | skill | area | yields | satiety | xp |');
  L.push('|---|---|---|---|---|---|');
  for (const a of ACTIVITIES) {
    const yields = Object.entries(a.yields)
      .map(([r, n]) => `${n} ${r}`)
      .join(', ');
    L.push(`| ${a.id} | ${a.skill} | ${a.area} | ${yields} | ${a.satietyCost} | ${a.xp} |`);
  }
  L.push('');

  L.push('## Estate map (spatial spine — D-093)');
  L.push('');
  L.push(`> Node ceiling: \`MAP_NODE_CEILING = ${MAP_NODE_CEILING}\` — the T0 hard cap on`);
  L.push('> node count (the graph stays a hamlet you can hold in your head; it grows in T1).');
  L.push('');
  L.push('| id | node | neighbours | revealFlag | dangerRing |');
  L.push('|---|---|---|---|---|');
  for (const n of MAP_NODES) {
    const node = n.kanji ? `${n.label} ${n.kanji}` : n.label;
    L.push(
      `| ${n.id} | ${node} | ${n.neighbors.join(', ')} | ${n.revealFlag ?? '—'} | ${n.dangerRing ? 'yes' : ''} |`,
    );
  }
  L.push('');

  L.push('## Weapons (T0 roster)');
  L.push('');
  L.push('| id | label | atk | speed | durability | archetype |');
  L.push('|---|---|---|---|---|---|');
  for (const w of WEAPONS) {
    L.push(
      `| ${w.id} | ${w.label} | ${w.baseAttack} | ${w.baseSpeed} | ${w.durabilityMax} | ${w.archetype} |`,
    );
  }
  L.push('');

  L.push('## Combat stances (glass-cannon ↔ tank axis — A2)');
  L.push('');
  L.push('> Defensive → aggressive (`STANCE_ORDER`). `chudan` (Balanced) is identity; only');
  L.push('> `atkMult` (outgoing) and `takenMult` (incoming, on the MC) remain post-A2.');
  L.push('');
  L.push('| id | atkMult | takenMult |');
  L.push('|---|---|---|');
  for (const id of STANCE_ORDER) {
    const m = STANCE_MODS[id];
    L.push(`| ${id} | ${m.atkMult} | ${m.takenMult} |`);
  }
  L.push('');

  L.push('## Bestiary (grounded — no belief-creatures)');
  L.push('');
  L.push('| id | label | level | coin | scripted |');
  L.push('|---|---|---|---|---|');
  for (const m of MOBS) {
    L.push(`| ${m.id} | ${m.label} | ${m.level} | ${m.coinReward} | ${m.scripted ? 'yes' : ''} |`);
  }
  L.push('');

  L.push('## Craft recipes (loot → craft — D-052)');
  L.push('');
  L.push('| id | output | inputs | label |');
  L.push('|---|---|---|---|');
  for (const r of RECIPES) {
    const inputs = Object.entries(r.inputs)
      .map(([mat, n]) => `${n} ${mat}`)
      .join(', ');
    L.push(`| ${r.id} | ${r.outputWeapon} | ${inputs} | ${r.label} |`);
  }
  L.push('');

  L.push('## Crafting materials');
  L.push('');
  L.push('| id | label | kanji |');
  L.push('|---|---|---|');
  for (const m of MATERIALS) L.push(`| ${m.id} | ${m.label} | ${m.kanji} |`);
  L.push('');

  L.push('## Material drops (foe → material)');
  L.push('');
  L.push('> Grindable foes only — the scripted grain-store wolf is never a loot source.');
  L.push('> Chance is integer fixed-point (`chanceNum / chanceDen`), rolled via the one loot RNG.');
  L.push('');
  L.push('| foe | material | qty | chance |');
  L.push('|---|---|---|---|');
  for (const [foe, d] of Object.entries(MATERIAL_DROPS)) {
    L.push(`| ${foe} | ${d.material} | ${d.qty} | ${d.chanceNum}/${d.chanceDen} |`);
  }
  L.push('');

  L.push('## Estate improvements (coin sink)');
  L.push('');
  L.push('| stage | label | coin | +satietyMax |');
  L.push('|---|---|---|---|');
  for (const e of ESTATE_STAGES) {
    L.push(`| E${e.stage} | ${e.label} | ${e.coinCost} | +${e.satietyMaxBonus} |`);
  }
  L.push('');

  L.push('## Market (T0 provisioning shop — D-008)');
  L.push('');
  L.push('> A small CAPPED coin sink (the TRADE taste). Every item carries a per-run');
  L.push('> `stockCap` so buying stays a MINORITY lane (≤ ⅓ of Estate & Wealth), never a');
  L.push('> primary income/output loop. The real village market arrives at T2.');
  L.push('');
  L.push('| id | label | coin | grants | stockCap |');
  L.push('|---|---|---|---|---|');
  for (const it of MARKET_ITEMS) {
    const grants = Object.entries(it.grants)
      .map(([r, n]) => `${n} ${r}`)
      .join(', ');
    L.push(`| ${it.id} | ${it.label} | ${it.coinCost} | ${grants} | ${it.stockCap} |`);
  }
  L.push('');

  L.push('## Rice sinks (D-107 Phase 2 — eat / store / sell)');
  L.push('');
  L.push('Rice is a REAL resource with three uses, so it never dead-ends (G-NO-DEAD-VALUES):');
  L.push('');
  L.push(
    `- **EAT** — \`eat_rice\` spends \`EAT_RICE_COST = ${balance.EAT_RICE_COST}\` rice for ` +
      `\`EAT_RICE_SATIETY = ${balance.EAT_RICE_SATIETY}\` work-stamina (a proper meal refuels ` +
      'MORE than a free `rest`, trading rice for readiness).',
  );
  L.push('- **STORE** — `deposit`/`withdraw` shelter rice in the kura (see the kura bank below).');
  L.push(
    '- **SELL** — `sell_rice` converts your carried rice to coin at a SEASON-swinging price (the ' +
      'coin faucet): DEAR in the lean spring, CHEAP at the autumn glut — a light store-vs-sell ' +
      'timing call (no live forex).',
  );
  L.push('');
  L.push('| season | coin per rice |');
  L.push('|---|---|');
  for (const s of SEASONS) L.push(`| ${s} | ${balance.riceSellPrice(s)} |`);
  L.push('');

  L.push('## The kura bank (carried vs banked)');
  L.push('');
  L.push('Resources come in two pools. **Carried** `resources` ride with the MC and are');
  L.push(
    '**at risk** — a combat loss bites carried coin + rice by `LOSS_COIN_FRAC` (0.2). **Banked**',
  );
  L.push('resources are sheltered in the kura storehouse: a loss never touches them, and a win');
  L.push('never moves them. `deposit` sweeps a carried resource into the bank and `withdraw`');
  L.push('draws it back; both are **spatial** — gated to the `kura` node, a no-op anywhere else');
  L.push('(walk home to store your haul). This is a mechanic, not a registry, so it has no table.');
  L.push('');

  L.push('## Surfaces (reveal registry)');
  L.push('');
  L.push('| id | kind |');
  L.push('|---|---|');
  for (const s of SURFACES) L.push(`| \`${s.id}\` | ${s.kind} |`);
  L.push('');

  L.push('## Cast — canonical display names (force-fictionalised)');
  L.push('');
  L.push('| key | name |');
  L.push('|---|---|');
  for (const [key, value] of Object.entries(NAMES)) L.push(`| ${key} | ${value} |`);
  L.push('');
  return L.join('\n');
}

const check = process.argv.includes('--check');
const content = generate();

if (check) {
  const existing = existsSync(OUT) ? readFileSync(OUT, 'utf-8') : '';
  if (existing !== content) {
    console.error(`gen:docs --check FAILED: ${OUT} is stale. Run \`npm run gen:docs\`.`);
    process.exit(1);
  }
  console.log('gen:docs --check: generated docs are up to date.');
} else {
  mkdirSync('docs/content', { recursive: true });
  writeFileSync(OUT, content, 'utf-8');
  console.log(`gen:docs: wrote ${OUT}.`);
}
process.exit(0);
