// t0-story.md emitter (FB-5 Ph4) — the one-page compiled READING script.
//
// The authoring files are already readable; this renders them as ONE page in
// play order — cold open → the three intro scenes → the R1…R7 rung beats —
// with rank titles pulled from RANKS and every choice inline, its effect
// annotations as small print. Written by gen-narrative beside the *.gen.ts
// modules and drift-checked the same way. This is the R8 "how to look" pointer.

import { RANKS } from '../../core/content/ranks';
import { NAMES } from '../../core/content/names';
import type {
  IntroSceneNode,
  NarrativeDoc,
  OptionNode,
  ProseLine,
  RungSceneNode,
  TopicNode,
} from './parse';

const RANK_BY_ID = new Map<string, (typeof RANKS)[number]>(RANKS.map((r) => [r.id, r]));

/** Resolve `{key}` interpolations + `@…` reuse refs into plain reading text. */
function makeResolver(docs: readonly NarrativeDoc[]): (text: string) => string {
  const coldOpen = new Map<string, string>();
  const dialogue = new Map<string, string>();
  for (const doc of docs) {
    for (const b of doc.blocks) {
      if (b.kind === 'prose') for (const e of b.entries) coldOpen.set(e.key, e.text);
      if (b.kind === 'dialogue') {
        for (const l of b.lines) dialogue.set(`${b.id}/${l.id}`, l.text);
      }
    }
  }
  const interpolate = (text: string): string =>
    text.replaceAll(/\{([a-zA-Z]+)\}/g, (whole, key: string) =>
      key in NAMES ? NAMES[key as keyof typeof NAMES] : whole,
    );
  return (text: string): string => {
    const cold = /^@cold-open\.([a-zA-Z]+)$/.exec(text);
    if (cold) return interpolate(coldOpen.get(cold[1]!) ?? text);
    const dlg = /^@dialogue\.(.+)$/.exec(text);
    if (dlg) return interpolate(dialogue.get(dlg[1]!) ?? text);
    return interpolate(text);
  };
}

type Resolver = (text: string) => string;

function proseLines(lines: readonly ProseLine[], resolve: Resolver): string[] {
  const out: string[] = [];
  for (const line of lines) {
    if (line.kind === 'narr') out.push(`> ${resolve(line.text)}`, '');
    else out.push(`**${line.speaker}:** ${resolve(line.text)}`, '');
  }
  return out;
}

function topicLines(t: TopicNode, resolve: Resolver): string[] {
  const gate = t.after ? ` *(after ${t.after})*` : '';
  const out: string[] = [`**Ask** — ${resolve(t.label)}${gate}`, ''];
  out.push(...proseLines(t.answer, resolve));
  return out;
}

function effectNotes(o: OptionNode, resolve: Resolver): string {
  const bits: string[] = [];
  if (o.memory) {
    bits.push(
      ...o.memory.map((m) => {
        const sign = m.warmthDelta < 0 ? '' : '+';
        const regard = m.regard ? ` (${m.regard})` : '';
        return `memory ${m.npc} ${sign}${m.warmthDelta}${regard}`;
      }),
    );
  }
  if (o.stat) bits.push(`stat +${o.stat.up} −${o.stat.down}`);
  if (o.perk) bits.push(`perk “${resolve(o.perk.name)}”`);
  if (o.flags) bits.push(`flags ${o.flags.join(', ')}`);
  if (o.bonus) bits.push(`⭐ +${o.bonus.amount} ${o.bonus.attr}`);
  if (o.stance) bits.push(`stance ${o.stance}`);
  return bits.length ? ` <small>· ${bits.join(' · ')}</small>` : '';
}

function sceneLines(scene: RungSceneNode | IntroSceneNode, resolve: Resolver): string[] {
  const out: string[] = [];
  out.push(...proseLines(scene.greeting, resolve));
  for (const t of scene.topics) out.push(...topicLines(t, resolve));
  const d = scene.decision!;
  out.push(`**Decide** — ${resolve(d.prompt)}`, '');
  for (const o of d.options) {
    const react = o.react!;
    const reactText =
      react.kind === 'speech'
        ? `**${react.speaker}:** ${resolve(react.text)}`
        : `*${resolve(react.text)}*`;
    out.push(`- ${resolve(o.label)}${effectNotes(o, resolve)}`, `  ${reactText}`, '');
  }
  return out;
}

/** Compile the whole narrative doc set into the t0-story.md reading page. */
export function emitStoryDoc(docs: readonly NarrativeDoc[]): string {
  const resolve = makeResolver(docs);
  const L: string[] = [
    '# T0 — the story (GENERATED)',
    '',
    '> GENERATED by `pnpm run gen:narrative` from the authoring sources in',
    '> [`src/core/content/narrative/`](../../src/core/content/narrative/) —',
    '> do not edit by hand; edit the narrative markdown and regenerate.',
    '> Play order: the cold open → the three intro scenes → the R1…R7 rung',
    '> beats. Choice effects render as small print; `⭐` marks the three rare',
    '> BQ2 bonuses.',
    '',
  ];

  // ── the cold open (keyed prose, in authored order) ──
  const prose = docs.flatMap((d) => d.blocks).find((b) => b.kind === 'prose');
  if (prose) {
    L.push('## The cold open', '');
    for (const e of prose.entries) {
      L.push(`> ${resolve(e.text)} <small>*(${e.key})*</small>`, '');
    }
  }

  // ── the intro scenes ──
  const intro = docs.flatMap((d) => d.blocks).filter((b) => b.kind === 'scene');
  const introTitles: Record<string, string> = {
    soan: `Sōan the physician`,
    dream: 'The dream-fragment',
    genemon: 'Genemon the steward',
  };
  for (let i = 0; i < intro.length; i++) {
    const scene = intro[i]!;
    L.push(`## Intro ${i + 1} · ${introTitles[scene.id] ?? scene.id}`, '');
    L.push(...sceneLines(scene, resolve));
  }

  // ── the rung beats ──
  for (const scene of docs.flatMap((d) => d.blocks).filter((b) => b.kind === 'rung')) {
    const rank = RANK_BY_ID.get(scene.rankKey);
    const title = rank ? `${rank.title} ${rank.kanji}` : scene.rankKey;
    L.push(`## ${scene.rankKey} · ${title}`, '');
    L.push(...sceneLines(scene, resolve));
  }

  // ── the hidden rung requirements (FB-121 / ADR-137) — the human's sign-off
  // artifact for the authored lists: flavor first (what the player feels), the
  // mechanical spec as small print (what the engine counts). ──
  const reqBlocks = docs.flatMap((d) => d.blocks).filter((b) => b.kind === 'requirements');
  if (reqBlocks.length > 0) {
    L.push('## The hidden rung requirements', '');
    L.push(
      '> The player never sees this list — only the rounded % bar and each',
      "> completion's flavor line. Counts are provisional (the FB-4 sim tunes",
      '> them; ADR-132).',
      '',
    );
    for (const b of reqBlocks) {
      const rank = RANK_BY_ID.get(b.rankKey);
      const title = rank ? `${rank.title} ${rank.kanji}` : b.rankKey;
      L.push(`### ${b.rankKey} · ${title}`, '');
      for (const r of b.reqs) {
        const s = r.spec;
        const mech =
          s.type === 'count'
            ? `${s.token} ×${s.target}`
            : s.type === 'flag'
              ? `flag ${s.flag}`
              : s.pred.kind === 'native'
                ? `native ${s.pred.key}`
                : s.pred.kind === 'belonging'
                  ? `own ${s.pred.id}`
                  : s.pred.kind === 'skill'
                    ? `skill ${s.pred.skill} ≥ ${s.pred.min}`
                    : `${s.pred.kind} ${s.pred.res} ≥ ${s.pred.min}`;
        L.push(`- ${resolve(r.flavor ?? '')} <small>*(${r.id} — ${mech})*</small>`);
      }
      L.push('');
    }
  }

  while (L[L.length - 1] === '') L.pop();
  return L.join('\n') + '\n';
}
