// GENERATED by `pnpm run gen:narrative` from src/core/content/narrative/takes/ — DO NOT EDIT.
// Hand edits here are drift by definition: edit the markdown source and regenerate
// (the gen-narrative verify gate rebuilds this file and byte-compares it).
// Data only — the types + helpers stay hand-written in storyTakes.ts, which re-exports this.

import type { StoryTakeBundle } from './storyTakes';
import { NAMES } from '../core/content/names';

export const STORY_TAKE_BUNDLES: readonly StoryTakeBundle[] = [
  {
    id: 'estate-build-beats',
    title: 'Phase-2 build beats (deed-source reveals + E1)',
    review: 'project/human-in-the-loop/review.md',
    rationale:
      'the ledger frame voices the mechanic itself (recognised deeds = entries worth recording); lean in the log, coherent with Genemon canon',
    takes: [
      {
        id: 'b',
        label: 'the land remembers',
        brief:
          'third-person earth-and-weather narrator — the world quietly answers the work; sensory, seasonal, unsentimental',
        scorecard:
          'strong imagery; ✘ too lush for repeated log lines (TST4 many-small-progressions legibility)',
        flavor: {
          estateSourceFields:
            'The new-broken paddy takes its first flooding and holds it, water standing level where the ground lay sour for years. The house books will say so tomorrow; the field says it tonight.',
          estateSourceStores:
            'The kura floor takes the weight of full bales and settles without a creak. A granary sits differently on its stones when there is something in it, and the whole yard knows the sound.',
          estateSourceWorkshop:
            'Shavings on the workshop floor, and one finished piece set out in the cold air to be counted. The smell of cut hinoki reaches the gate before the news does.',
          estateSourceWatch:
            'By morning the rain has taken the blood, and the path to the storehouse lies quiet. The dogs sleep through the night now; the dark keeps a wider distance from the walls.',
          estateSourceTreasury:
            "Rice grown on this ground goes out the gate as silver, and the entry dries slowly in the house books. The land fed the house through the lean years; now it begins to pay the house's debts.",
          estateStands:
            "The last ridge-beam is pegged home, and the frame stops answering the wind. On foundation stones that outlasted frost, flood, and the creditor's seal, the Kurosawa estate stands — and the ground takes the full weight of the house again, as a thing it had not forgotten.",
        },
      },
      {
        id: 'c',
        label: "the heir's private reckoning",
        brief:
          'MC inward first person, diary-of-a-samurai — each source a realization his labour carries the name; closes on the mendHint vow kept',
        scorecard:
          'strong mendHint callback; ✘ first-person "I" clashes with the log\'s narrator-voice convention (FB-91/93)',
        flavor: {
          estateSourceFields:
            "Mud to the knee since first light — and tonight the yield goes down under the house's name. My work carries that name now. Let it carry.",
          estateSourceStores:
            'The granary takes what I hauled, and the house is one bad winter safer for it. Set it down plainly: full stores, my shoulders.',
          estateSourceWorkshop:
            "The workshop's first piece, finished, fit to sell without shame. Made under this roof — by hands this house once hired by the day.",
          estateSourceWatch:
            'The fight is won, and the gate stands quieter for it. A house that is defended is a house again; I will keep it so.',
          estateSourceTreasury:
            'Rice sold, and the sum entered in the house books in my own hand. A hired man marks a tally. A son keeps the ledger.',
          estateStands:
            'The estate stands. Once I told myself: climb higher, then set it right — it is set right, and I lived to stand in its shadow.',
        },
      },
    ],
  },

  {
    id: 'fb121-req-flavor',
    title: 'FB-121 requirement-completion flavor (23 lines)',
    review: 'project/human-in-the-loop/review.md',
    rationale:
      'picked PER RUNG (human bundle call): R0 C · R1 A · R2 B · R3 C · R4 A · R5 A · R6 C · R7 C — spoken lines land where a granter leans in; house/material registers carry the grind. Canon carries the mixed pick; each take here is a full coherent alternate voice.',
    takes: [
      {
        id: 'a',
        label: 'the house notices',
        brief:
          'third-person household observation — the people, ledgers and habits of the house registering him',
        scorecard:
          '23 strong lines; ✘ canon order — named Tōzō at R2 + Chiyo at R3 (before their story introductions)',
        reqFlavor: {
          'rake-the-spill': `${NAMES.elder} says nothing of the spilled rice, only that the man raking it does not stop.`,
          'take-to-the-fields':
            'The paddy women no longer point out which rows are his; he has learned them.',
          'a-porters-back':
            'At the gate the porters shift a strap for him without being asked, as they do among their own.',
          'learn-the-woodlot': `${NAMES.smith} hears the axe-fall from the smithy and no longer comes out to correct it.`,
          'walk-the-hills': 'The kitchen stops picking through his basket before cooking from it.',
          'keep-the-stores-moving': `${NAMES.elder}'s tally sticks move faster on the days the new man carries.`,
          'face-the-wolf':
            'He is pulled from the grain-store bloodied, and the talk in the house that night is that he stood.',
          'clear-the-kura-rats': `${NAMES.steward} finds no droppings in the kura and asks ${NAMES.elder}, once, who saw to it.`,
          'drive-off-the-thieves':
            'The monkeys take their screaming elsewhere, and the paddy edge goes quiet again.',
          'keep-the-rows':
            'The rows come in even though he wears a blade to work them now, and the old hands note it.',
          'timber-for-the-palisade': `Split stakes pile by the gate faster than ${NAMES.drillmaster} can set them.`,
          'the-stores-know-you':
            'New porters are told to watch how he stacks; nobody remembers deciding that.',
          'mend-your-own-blade': `${NAMES.smith} turns the mended edge to the light and hands it back without a word of correction.`,
          'a-hundred-mon-held':
            'The house learns he keeps coin of his own, strung and counted, spent on nothing foolish.',
          'past-the-danger-line':
            "He comes back from past the charcoal-burners' marker so often the kitchen stops waiting up.",
          'the-paddies-still-first': `Whatever else he is now, the paddies get his mornings first, and ${NAMES.elder} sees that they do.`,
          'a-made-corner':
            'There is bedding in the north corner, bought with his own coin, and the maids sweep around it now.',
          'the-ledgers-agree':
            'The count in the book and the count on the kura floor agree, and it is his carrying between them.',
          'three-hundred-mon-steady': `His coin-string thickens and stays; ${NAMES.steward} hears of it and is not surprised.`,
          'coin-into-the-works':
            'His own coin goes into the kura-works, and the house understands it was never leaving.',
          'the-fields-run-on-you': `The planting order goes out under his eye now, and ${NAMES.elder} lets it.`,
          'the-woodlot-runs-on-you': `${NAMES.smith} banks the smithy fire against wood he no longer has to ask for.`,
          'a-granary-against-winter': `Rice against winter sits banked in the granary, and ${NAMES.lord} is told whose hands filled it.`,
        },
      },
      {
        id: 'b',
        label: 'the work itself speaks',
        brief: 'material evidence — tools, ground, grain, body; people only at the edges',
        scorecard:
          "canon-clean everywhere; the corpus's best wolf line; a shade impersonal at the granter rungs",
        reqFlavor: {
          'rake-the-spill':
            "By dawn the spilled rice lies in even rows across the courtyard, and the rake's teeth are worn bright.",
          'take-to-the-fields':
            'The paddy mud has learned the shape of his feet; the rows run straighter where he has passed.',
          'a-porters-back':
            "A track shows in the forecourt stones now, cart to gate, the width of one man's stride.",
          'learn-the-woodlot':
            'The axe haft darkens where his grip has settled, and the stumps at the woodlot edge stand cut clean.',
          'walk-the-hills':
            'The near hills give up bracken and mushrooms without a search; the basket comes home heavy before noon.',
          'keep-the-stores-moving':
            'Bales pass the gate and none sit long; the storehouse floor shows bare wood where sacks once rotted.',
          'face-the-wolf':
            'There is blood on the grain-store threshold, most of it his, and the rice behind the door untouched.',
          'clear-the-kura-rats':
            'The kura goes quiet at night; only shed gray fur in the corners says the rats were ever there.',
          'drive-off-the-thieves':
            'The paddy edges keep their ears of rice again, and nothing chatters from the trees at dusk.',
          'keep-the-rows':
            "A spear leans in the mud at the field's edge, and still the rows come up green and even.",
          'timber-for-the-palisade':
            'Fresh-cut stakes stand seasoning in the yard, enough to close the gaps where the fence had rotted.',
          'the-stores-know-you':
            'Every bale in the kura sits where a hand can find it in the dark; dust lies only where nothing moves.',
          'mend-your-own-blade':
            'The blade carries a new-hammered edge over its old nicks, oiled and wrapped by the hand that dulled it.',
          'a-hundred-mon-held':
            'Under a loose board waits a full string of copper, tied off, heavier than the month before.',
          'past-the-danger-line':
            'His footprints go on past the shrine rope where the other baskets turn back, and they come home full.',
          'the-paddies-still-first':
            'The deep hills can wait; the paddies are weeded first, and the water sits level from bund to bund.',
          'a-made-corner':
            'New-stuffed bedding lies folded in a corner behind the kitchen, the first thing under this roof that is his.',
          'the-ledgers-agree':
            'The tallies on the kura door and the bales inside come to the same count, season after season.',
          'three-hundred-mon-steady':
            'The strings of copper in his box no longer fit one hand; they sit undisturbed, gathering weight.',
          'coin-into-the-works':
            "New timber and fresh plaster stand in the kura works, paid from a labourer's own string of coin.",
          'the-fields-run-on-you':
            'The paddies flood and drain to his reckoning now; the water follows the ditches he keeps.',
          'the-woodlot-runs-on-you':
            'The woodpile stands stacked past the eaves before first frost, split to the size the stoves like.',
          'a-granary-against-winter':
            'Rice sits banked to the joists in the granary, sealed against whatever snow the year intends.',
        },
      },
      {
        id: 'c',
        label: 'a word let drop',
        brief: 'overheard/reported remarks, minimally framed; speakers follow the granter arc',
        scorecard:
          'the strongest single lines (R0 dawn, R7 winter); ✘ canon order — Kihei at R2, Chiyo at R4/R5',
        reqFlavor: {
          'rake-the-spill': `"Dawn, and he is still raking," ${NAMES.elder} says to the dark, as if the dark had asked.`,
          'take-to-the-fields': `"The paddies look tended for once," ${NAMES.elder} lets fall at the well, naming no one.`,
          'a-porters-back':
            '"Born under a load, that one," an old porter is heard to say at the gate-forecourt.',
          'learn-the-woodlot': `"The stacks stand square this year," ${NAMES.elder} notes in passing, as though the wood had done it itself.`,
          'walk-the-hills':
            '"He knows the hill paths better than the charcoal men now," the kitchen says among itself.',
          'keep-the-stores-moving': `"Ask the new hand," ${NAMES.elder} says, when the count of the store-room is wanted.`,
          'face-the-wolf': `"He stood," ${NAMES.drillmaster} says of the wolf, and says nothing else.`,
          'clear-the-kura-rats': `"Quiet in the kura tonight," ${NAMES.drillmaster} lets drop, cleaning his blade by lamplight.`,
          'drive-off-the-thieves': `"The monkeys have learned his shape," ${NAMES.drillmaster} is heard to say, almost pleased.`,
          'keep-the-rows': `"Watch or no watch, his rows never fell behind," ${NAMES.elder} says over the evening rice.`,
          'timber-for-the-palisade': `"The palisade wood is his cutting," ${NAMES.drillmaster} says, striking a post with the flat of his hand.`,
          'the-stores-know-you': `"The stores go where he says they go," ${NAMES.steward} observes, tallying without looking up.`,
          'mend-your-own-blade': `"He mends his own now," ${NAMES.smith} says, and turns back to the forge.`,
          'a-hundred-mon-held': `"He keeps his coin better than some keep their name," ${NAMES.steward} remarks over the ledger.`,
          'past-the-danger-line':
            '"Past the old markers, and back again whole," the hill-cutters say of him, shaking their heads.',
          'the-paddies-still-first': `"Deep hills or no, the paddies come first with him," ${NAMES.elder} says, as if settling an argument.`,
          'a-made-corner': `"Bedding of his own," ${NAMES.steward} says, passing his corner, "so he means to stay."`,
          'the-ledgers-agree': `"The ledgers agree tonight," ${NAMES.steward} says, which is her whole praise.`,
          'three-hundred-mon-steady': `"His purse holds steady," ${NAMES.steward} lets fall, "which is more than this house has managed."`,
          'coin-into-the-works': `"He put his own coin into the kura-works," ${NAMES.steward} tells ${NAMES.elder}, twice, to be sure he heard.`,
          'the-fields-run-on-you': `"The fields no longer wait on my orders," ${NAMES.lord} says from the veranda, "they wait on his."`,
          'the-woodlot-runs-on-you': `"Even the woodlot answers to him," ${NAMES.drillmaster} says to ${NAMES.elder}, who does not disagree.`,
          'a-granary-against-winter': `"There is rice against winter," ${NAMES.lord} says, slowly, as if the words were new to him.`,
        },
      },
    ],
  },
];
